(in-package #:ethereum-lisp.test)

(deftest memory-key-value-database-put-get-delete
  (let ((database (make-memory-key-value-database))
        (key #(1 2 3))
        (value (copy-seq #(4 5 6))))
    (multiple-value-bind (missing present-p)
        (kv-get database key :missing)
      (is (eq :missing missing))
      (is (not present-p)))
    (kv-put database key value)
    (setf (aref value 0) 9)
    (multiple-value-bind (stored present-p)
        (kv-get database key)
      (is present-p)
      (is (bytes= #(4 5 6) stored))
      (setf (aref stored 0) 9))
    (multiple-value-bind (stored present-p)
        (kv-get database key)
      (is present-p)
      (is (bytes= #(4 5 6) stored)))
    (is (kv-delete database key))
    (multiple-value-bind (missing present-p)
        (kv-get database key :missing)
      (is (eq :missing missing))
      (is (not present-p)))
    (is (not (kv-delete database key)))))

(deftest memory-key-value-database-applies-write-batches-in-order
  (let ((database (make-memory-key-value-database))
        (batch (make-kv-write-batch)))
    (kv-put database #(1) #(1))
    (kv-batch-put batch #(1) #(2))
    (kv-batch-put batch #(2) #(3))
    (kv-batch-delete batch #(1))
    (kv-apply-batch database batch)
    (multiple-value-bind (value present-p)
        (kv-get database #(1))
      (declare (ignore value))
      (is (not present-p)))
    (multiple-value-bind (value present-p)
        (kv-get database #(2))
      (is present-p)
      (is (bytes= #(3) value)))))

(deftest memory-key-value-database-iterates-sorted-ranges
  (let ((database (make-memory-key-value-database)))
    (kv-put database #(3) #(30))
    (kv-put database #(1) #(10))
    (kv-put database #(2) #(20))
    (let ((iterator (kv-iterator database :start #(2) :end #(4))))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (is present-p)
        (is (bytes= #(2) key))
        (is (bytes= #(20) value)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (is present-p)
        (is (bytes= #(3) key))
        (is (bytes= #(30) value)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (declare (ignore key value))
        (is (not present-p))))
    (let ((iterator (kv-iterator database :reverse-p t)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (declare (ignore value))
        (is present-p)
        (is (bytes= #(3) key))))))

(deftest file-key-value-database-persists-chain-records
  (let* ((path
           (merge-pathnames
            (make-pathname
             :name (format nil "ethereum-lisp-kv-~A" (gensym))
             :type "sexp")
            #P"/private/tmp/"))
         (block-key #(1 0))
         (header-key #(2 0))
         (receipt-key #(3 0)))
    (unwind-protect
         (progn
           (let ((database (make-file-key-value-database path))
                 (batch (make-kv-write-batch)))
             (kv-put database block-key #(11 12 13))
             (kv-batch-put batch header-key #(21 22))
             (kv-batch-put batch receipt-key #(31 32 33))
             (kv-apply-batch database batch))
           (let ((database (make-file-key-value-database path)))
             (multiple-value-bind (value present-p)
                 (kv-get database block-key)
               (is present-p)
               (is (bytes= #(11 12 13) value)))
             (multiple-value-bind (value present-p)
                 (kv-get database header-key)
               (is present-p)
               (is (bytes= #(21 22) value)))
             (multiple-value-bind (value present-p)
                 (kv-get database receipt-key)
               (is present-p)
               (is (bytes= #(31 32 33) value)))
             (let ((iterator (kv-iterator database :start #(2) :end #(4))))
               (multiple-value-bind (key value present-p)
                   (funcall iterator)
                 (is present-p)
                 (is (bytes= header-key key))
                 (is (bytes= #(21 22) value)))
               (multiple-value-bind (key value present-p)
                   (funcall iterator)
                 (is present-p)
                 (is (bytes= receipt-key key))
                 (is (bytes= #(31 32 33) value))))
             (kv-delete database header-key))
           (let ((database (make-file-key-value-database path)))
             (multiple-value-bind (value present-p)
                 (kv-get database header-key)
               (declare (ignore value))
               (is (not present-p)))
             (multiple-value-bind (value present-p)
                 (kv-get database block-key)
               (is present-p)
               (is (bytes= #(11 12 13) value)))))
      (when (probe-file path)
        (delete-file path)))))

(deftest file-key-value-database-replaces-through-temp-file
  (let* ((name (format nil "ethereum-lisp-kv-replace-~A" (gensym)))
         (path
           (merge-pathnames
            (make-pathname :name name :type "sexp")
            #P"/private/tmp/"))
         (temp-pattern
           (merge-pathnames
            (make-pathname
             :name (format nil ".~A.*" name)
             :type "sexp")
            #P"/private/tmp/")))
    (unwind-protect
         (progn
           (let ((database (make-file-key-value-database path))
                 (batch (make-kv-write-batch)))
             (kv-put database #(1) #(1))
             (kv-batch-put batch #(2) #(2))
             (kv-batch-put batch #(3) #(3))
             (kv-apply-batch database batch)
             (kv-put database #(1) #(9)))
           (is (null (directory temp-pattern)))
           (let ((database (make-file-key-value-database path)))
             (multiple-value-bind (value present-p)
                 (kv-get database #(1))
               (is present-p)
               (is (bytes= #(9) value)))
             (multiple-value-bind (value present-p)
                 (kv-get database #(2))
               (is present-p)
               (is (bytes= #(2) value)))))
      (when (probe-file path)
        (delete-file path))
      (dolist (temp-path (directory temp-pattern))
        (when (probe-file temp-path)
          (delete-file temp-path))))))

(deftest chain-record-keys-namespace-chain-data
  (let ((database (make-memory-key-value-database))
        (block-hash (make-byte-vector 32 :initial-element #xaa))
        (receipt-hash (make-byte-vector 32 :initial-element #xbb)))
    (kv-put-chain-record database :block block-hash #(1 2 3))
    (kv-put-chain-record database :receipt receipt-hash #(4 5 6))
    (kv-put-chain-record database :canonical-hash 10 #(10))
    (kv-put-chain-record database :canonical-hash 2 #(2))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :block block-hash)
      (is present-p)
      (is (bytes= #(1 2 3) value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :receipt receipt-hash)
      (is present-p)
      (is (bytes= #(4 5 6) value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :header block-hash :missing)
      (is (eq :missing value))
      (is (not present-p)))
    (let ((canonical-records (kv-chain-records database :canonical-hash)))
      (is (= 2 (length canonical-records)))
      (is (bytes= (kv-chain-record-key :canonical-hash 2)
                  (caar canonical-records)))
      (is (bytes= #(2) (cdar canonical-records)))
      (is (bytes= (kv-chain-record-key :canonical-hash 10)
                  (caadr canonical-records)))
      (is (bytes= #(10) (cdadr canonical-records))))
    (is (kv-delete-chain-record database :block block-hash))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :block block-hash :missing)
      (is (eq :missing value))
      (is (not present-p)))))

(deftest chain-record-typed-index-helpers-round-trip
  (let ((database (make-memory-key-value-database))
        (block-hash-a (make-byte-vector 32 :initial-element #x0a))
        (block-hash-b (make-byte-vector 32 :initial-element #x0b))
        (block-hash-c (make-byte-vector 32 :initial-element #x0c)))
    (kv-put-chain-canonical-hash database 10 block-hash-b)
    (kv-put-chain-canonical-hash database 2 block-hash-a)
    (kv-put-chain-checkpoint database :head block-hash-b)
    (kv-put-chain-checkpoint database "safe" block-hash-a)
    (multiple-value-bind (value present-p)
        (kv-get-chain-canonical-hash database 10)
      (is present-p)
      (is (bytes= block-hash-b value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-checkpoint database :head)
      (is present-p)
      (is (bytes= block-hash-b value)))
    (let ((canonical-hashes (kv-chain-canonical-hashes database)))
      (is (= 2 (length canonical-hashes)))
      (is (= 2 (caar canonical-hashes)))
      (is (bytes= block-hash-a (cdar canonical-hashes)))
      (is (= 10 (caadr canonical-hashes)))
      (is (bytes= block-hash-b (cdadr canonical-hashes))))
    (let ((batch (make-kv-write-batch)))
      (kv-batch-put-chain-canonical-hash batch 12 block-hash-c)
      (kv-batch-put-chain-checkpoint batch :finalized block-hash-a)
      (kv-batch-delete-chain-checkpoint batch :safe)
      (kv-apply-batch database batch))
    (let ((canonical-hashes (kv-chain-canonical-hashes database))
          (checkpoints (kv-chain-checkpoints database)))
      (is (= 3 (length canonical-hashes)))
      (is (= 12 (caaddr canonical-hashes)))
      (is (bytes= block-hash-c (cdaddr canonical-hashes)))
      (is (= 2 (length checkpoints)))
      (is (bytes= block-hash-b
                  (cdr (assoc :head checkpoints))))
      (is (bytes= block-hash-a
                  (cdr (assoc :finalized checkpoints))))
      (is (not (assoc :safe checkpoints))))
    (is (kv-delete-chain-canonical-hash database 2))
    (multiple-value-bind (value present-p)
        (kv-get-chain-canonical-hash database 2 :missing)
      (is (eq :missing value))
      (is (not present-p)))
    (signals error
      (kv-put-chain-checkpoint database :unsafe block-hash-a))))

(deftest file-key-value-database-persists-chain-record-namespace
  (let* ((path
           (merge-pathnames
            (make-pathname
             :name (format nil "ethereum-lisp-chain-records-~A" (gensym))
             :type "sexp")
            #P"/private/tmp/"))
         (hash (make-byte-vector 32 :initial-element #x44)))
    (unwind-protect
         (progn
           (let ((database (make-file-key-value-database path)))
             (kv-put-chain-record database :block hash #(1 1 1))
             (kv-put-chain-record database :canonical-hash 1 #(4 4))
             (kv-put-chain-record database :canonical-hash 3 #(6 6)))
           (let ((database (make-file-key-value-database path)))
             (multiple-value-bind (value present-p)
                 (kv-get-chain-record database :block hash)
               (is present-p)
               (is (bytes= #(1 1 1) value)))
             (let ((records (kv-chain-records database :canonical-hash)))
               (is (= 2 (length records)))
               (is (bytes= #(4 4) (cdar records)))
               (is (bytes= #(6 6) (cdadr records))))))
      (when (probe-file path)
        (delete-file path)))))

(deftest file-key-value-database-persists-typed-chain-indexes
  (let* ((path
           (merge-pathnames
            (make-pathname
             :name (format nil "ethereum-lisp-chain-indexes-~A" (gensym))
             :type "sexp")
            #P"/private/tmp/"))
         (head-hash (make-byte-vector 32 :initial-element #x31))
         (safe-hash (make-byte-vector 32 :initial-element #x32))
         (side-hash (make-byte-vector 32 :initial-element #x33)))
    (unwind-protect
         (progn
           (let ((database (make-file-key-value-database path))
                 (batch (make-kv-write-batch)))
             (kv-batch-put-chain-canonical-hash batch 1 safe-hash)
             (kv-batch-put-chain-canonical-hash batch 2 head-hash)
             (kv-batch-put-chain-checkpoint batch :head head-hash)
             (kv-batch-put-chain-checkpoint batch :safe safe-hash)
             (kv-batch-put-chain-checkpoint batch :finalized safe-hash)
             (kv-apply-batch database batch)
             (kv-put-chain-canonical-hash database 99 side-hash)
             (kv-delete-chain-canonical-hash database 99))
           (let ((database (make-file-key-value-database path)))
             (let ((canonical-hashes (kv-chain-canonical-hashes database))
                   (checkpoints (kv-chain-checkpoints database)))
               (is (= 2 (length canonical-hashes)))
               (is (= 1 (caar canonical-hashes)))
               (is (bytes= safe-hash (cdar canonical-hashes)))
               (is (= 2 (caadr canonical-hashes)))
               (is (bytes= head-hash (cdadr canonical-hashes)))
               (is (= 3 (length checkpoints)))
               (is (bytes= head-hash
                           (cdr (assoc :head checkpoints))))
               (is (bytes= safe-hash
                           (cdr (assoc :safe checkpoints))))
               (is (bytes= safe-hash
                           (cdr (assoc :finalized checkpoints)))))
             (multiple-value-bind (value present-p)
                 (kv-get-chain-canonical-hash database 99 :missing)
               (is (eq :missing value))
               (is (not present-p)))))
      (when (probe-file path)
        (delete-file path)))))

(deftest chain-record-write-batches-apply-atomically
  (let ((database (make-memory-key-value-database))
        (batch (make-kv-write-batch))
        (block-hash (make-byte-vector 32 :initial-element #x11))
        (receipt-hash (make-byte-vector 32 :initial-element #x22)))
    (kv-put-chain-record database :receipt receipt-hash #(9 9))
    (kv-batch-put-chain-record batch :block block-hash #(1 2 3))
    (kv-batch-put-chain-record batch :header block-hash #(4 5 6))
    (kv-batch-put-chain-record batch :canonical-hash 7 block-hash)
    (kv-batch-delete-chain-record batch :receipt receipt-hash)
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :block block-hash :missing)
      (is (eq :missing value))
      (is (not present-p)))
    (kv-apply-batch database batch)
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :block block-hash)
      (is present-p)
      (is (bytes= #(1 2 3) value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :header block-hash)
      (is present-p)
      (is (bytes= #(4 5 6) value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :canonical-hash 7)
      (is present-p)
      (is (bytes= block-hash value)))
    (multiple-value-bind (value present-p)
        (kv-get-chain-record database :receipt receipt-hash :missing)
      (is (eq :missing value))
      (is (not present-p)))
    (let ((entries (kv-chain-record-entries database :canonical-hash)))
      (is (= 1 (length entries)))
      (is (bytes= #(0 0 0 0 0 0 0 7) (caar entries)))
      (is (bytes= block-hash (cdar entries))))))

(deftest file-key-value-database-persists-chain-record-batches
  (let* ((path
           (merge-pathnames
            (make-pathname
             :name (format nil "ethereum-lisp-chain-record-batch-~A"
                           (gensym))
             :type "sexp")
            #P"/private/tmp/"))
         (block-hash-a (make-byte-vector 32 :initial-element #x0a))
         (block-hash-b (make-byte-vector 32 :initial-element #x0b))
         (receipt-hash (make-byte-vector 32 :initial-element #x0c)))
    (unwind-protect
         (progn
           (let ((database (make-file-key-value-database path))
                 (batch (make-kv-write-batch)))
             (kv-put-chain-record database :receipt receipt-hash #(8 8))
             (kv-batch-put-chain-record batch :block block-hash-a #(1))
             (kv-batch-put-chain-record batch :block block-hash-b #(2))
             (kv-batch-put-chain-record
              batch :canonical-hash 2 block-hash-b)
             (kv-batch-put-chain-record
              batch :canonical-hash 1 block-hash-a)
             (kv-batch-delete-chain-record batch :receipt receipt-hash)
             (kv-apply-batch database batch))
           (let ((database (make-file-key-value-database path)))
             (multiple-value-bind (value present-p)
                 (kv-get-chain-record database :block block-hash-a)
               (is present-p)
               (is (bytes= #(1) value)))
             (multiple-value-bind (value present-p)
                 (kv-get-chain-record database :receipt receipt-hash :missing)
               (is (eq :missing value))
               (is (not present-p)))
             (let ((entries
                     (kv-chain-record-entries database :canonical-hash)))
               (is (= 2 (length entries)))
               (is (bytes= #(0 0 0 0 0 0 0 1) (caar entries)))
               (is (bytes= block-hash-a (cdar entries)))
               (is (bytes= #(0 0 0 0 0 0 0 2) (caadr entries)))
               (is (bytes= block-hash-b (cdadr entries))))))
      (when (probe-file path)
        (delete-file path)))))
