(in-package #:ethereum-lisp.test)

(deftest memory-key-value-database-put-get-delete
  (let ((database (make-memory-key-value-database))
        (key #(1 2 3))
        (value (copy-seq #(4 5 6))))
    (multiple-value-bind (missing present-p)
        (kv-get database key :missing)
      (is (eq :missing missing))
      (is (not present-p)))
    (kv-put database key value)
    (setf (aref value 0) 9)
    (multiple-value-bind (stored present-p)
        (kv-get database key)
      (is present-p)
      (is (bytes= #(4 5 6) stored))
      (setf (aref stored 0) 9))
    (multiple-value-bind (stored present-p)
        (kv-get database key)
      (is present-p)
      (is (bytes= #(4 5 6) stored)))
    (is (kv-delete database key))
    (multiple-value-bind (missing present-p)
        (kv-get database key :missing)
      (is (eq :missing missing))
      (is (not present-p)))
    (is (not (kv-delete database key)))))

(deftest memory-key-value-database-applies-write-batches-in-order
  (let ((database (make-memory-key-value-database))
        (batch (make-kv-write-batch)))
    (kv-put database #(1) #(1))
    (kv-batch-put batch #(1) #(2))
    (kv-batch-put batch #(2) #(3))
    (kv-batch-delete batch #(1))
    (kv-apply-batch database batch)
    (multiple-value-bind (value present-p)
        (kv-get database #(1))
      (declare (ignore value))
      (is (not present-p)))
    (multiple-value-bind (value present-p)
        (kv-get database #(2))
      (is present-p)
      (is (bytes= #(3) value)))))

(deftest memory-key-value-database-iterates-sorted-ranges
  (let ((database (make-memory-key-value-database)))
    (kv-put database #(3) #(30))
    (kv-put database #(1) #(10))
    (kv-put database #(2) #(20))
    (let ((iterator (kv-iterator database :start #(2) :end #(4))))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (is present-p)
        (is (bytes= #(2) key))
        (is (bytes= #(20) value)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (is present-p)
        (is (bytes= #(3) key))
        (is (bytes= #(30) value)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (declare (ignore key value))
        (is (not present-p))))
    (let ((iterator (kv-iterator database :reverse-p t)))
      (multiple-value-bind (key value present-p)
          (funcall iterator)
        (declare (ignore value))
        (is present-p)
        (is (bytes= #(3) key))))))
