(defpackage #:ethereum-lisp.txpool.application
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool)
  (:export
   #:txpool-admission-policy
   #:make-txpool-admission-policy
   #:txpool-admission-policy-allow-unprotected-transactions-p
   #:txpool-admission-policy-price-limit
   #:txpool-admission-policy-price-bump-percent
   #:txpool-admission-policy-account-slot-limit
   #:txpool-admission-policy-global-slot-limit
   #:txpool-admission-policy-account-queue-limit
   #:txpool-admission-policy-global-queue-limit
   #:txpool-admission-policy-local-addresses
   #:txpool-admission-policy-no-local-exemptions-p
   #:txpool-local-transaction-p
   #:txpool-local-transaction-predicate
   #:txpool-admit-transaction))

(defpackage #:ethereum-lisp.engine-api
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.strings
        #:ethereum-lisp.types
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.node-store
        #:ethereum-lisp.txpool
        #:ethereum-lisp.canonical-chain
        #:ethereum-lisp.engine
        #:ethereum-lisp.execution
        #:ethereum-lisp.execution-service)
  (:export
   #:+engine-rpc-capabilities+
   #:engine-rpc-capabilities
   #:+engine-rpc-client-version+
   #:engine-rpc-client-version
   #:engine-rpc-transition-configuration-object
   #:engine-rpc-executable-data-from-object
   #:engine-rpc-executable-data-object
   #:engine-rpc-withdrawal-object
   #:engine-rpc-payload-status-object
   #:engine-rpc-forkchoice-state-from-object
   #:engine-rpc-forkchoice-response-object
   #:engine-rpc-handle-get-payload-v1
   #:engine-rpc-handle-forkchoice-updated-v1
   #:engine-rpc-build-viable-prepared-payload
   #:engine-rpc-pending-build-transactions
   #:engine-rpc-improve-prepared-payload
   #:engine-rpc-improve-open-payloads
   #:engine-rpc-engine-method-p
   #:engine-rpc-required-eth-method-p
   #:+engine-rpc-required-eth-methods+
   #:engine-rpc-public-method-p
   #:engine-rpc-admin-method-p
   #:engine-rpc-any-method-p
   #:engine-rpc-error
   #:engine-rpc-error-code
   #:engine-rpc-error-message
   #:engine-rpc-error-data
   #:engine-rpc-fail-with-data
   #:+engine-rpc-error-execution-reverted+
   #:engine-rpc-handle-engine-method))

(defpackage #:ethereum-lisp.public-api
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.genesis
        #:ethereum-lisp.accounts
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store.state
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool
        #:ethereum-lisp.state
        #:ethereum-lisp.state-proof-json
        #:ethereum-lisp.evm
        #:ethereum-lisp.execution
        #:ethereum-lisp.execution-service
        #:ethereum-lisp.txpool.application
        #:ethereum-lisp.p2p
        #:ethereum-lisp.engine-api)
  (:export
   #:engine-rpc-handle-public-method
   #:admin-backend
   #:admin-backend-p
   #:make-admin-backend
   #:admin-backend-node-info
   #:admin-backend-peers
   #:admin-backend-add-peer
   #:admin-backend-remove-peer
   #:admin-backend-peer-count
   #:admin-backend-listening-p
   #:eth-rpc-subscription
   #:eth-rpc-subscription-id
   #:eth-rpc-subscription-kind
   #:eth-rpc-subscription-registry
   #:make-eth-rpc-subscription-registry
   #:eth-rpc-subscription-registry-subscriptions
   #:eth-rpc-subscription-count
   #:eth-rpc-handle-eth-subscribe
   #:eth-rpc-handle-eth-unsubscribe
   #:eth-rpc-subscription-notification-json
   #:eth-rpc-subscription-new-heads
   #:eth-rpc-subscription-pending-hashes
   #:eth-rpc-subscription-poll))

(defpackage #:ethereum-lisp.rpc
  (:use #:cl
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.engine-api
        #:ethereum-lisp.public-api)
  (:export
   #:rpc-context
   #:make-rpc-context
   #:rpc-context-store
   #:rpc-context-config
   #:rpc-context-import-function
   #:rpc-context-new-payload-persistence-function
   #:rpc-context-network-id
   #:rpc-context-coinbase
   #:rpc-context-gas-limit-target
   #:rpc-context-allowed-method-p
   #:rpc-context-rebind
   #:rpc-context-with-txpool-now
   #:rpc-handle-request
   #:rpc-handle-request-value
   #:rpc-handle-request-string
   #:rpc-handle-request-json
   #:engine-rpc-handle-request
   #:engine-rpc-handle-request-value
   #:engine-rpc-handle-request-string
   #:engine-rpc-handle-request-json))

(defpackage #:ethereum-lisp.rpc-http
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.strings
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.node-state
        #:ethereum-lisp.engine-api
        #:ethereum-lisp.rpc)
  (:export
   #:+engine-rpc-http-accepted-content-types+
   #:engine-rpc-http-accepted-content-type-p
   #:*engine-rpc-http-max-body-bytes*
   #:*engine-rpc-http-max-header-bytes*
   #:*engine-rpc-http-max-header-lines*
   #:*engine-rpc-http-request-timeout-seconds*
   #:*engine-rpc-http-max-concurrent-connections*
   #:+engine-rpc-default-http-host+
   #:+engine-rpc-default-http-port+
   #:+engine-rpc-jwt-expiry-seconds+
   #:engine-rpc-http-service
   #:make-engine-rpc-http-service
   #:engine-rpc-http-service-host
   #:engine-rpc-http-service-port
   #:engine-rpc-http-service-store
   #:engine-rpc-http-service-config
   #:engine-rpc-http-service-jwt-secret
   #:engine-rpc-http-service-now-provider
   #:engine-rpc-http-service-import-function
   #:engine-rpc-http-service-new-payload-persistence-function
   #:engine-rpc-http-service-telemetry-sink
   #:engine-rpc-http-service-allowed-method-p
   #:engine-rpc-http-service-network-id
   #:engine-rpc-http-service-coinbase
   #:engine-rpc-http-service-rpc-context
   #:engine-rpc-http-service-rpc-prefix
   #:engine-rpc-http-service-endpoint
   #:engine-rpc-http-connection
   #:make-engine-rpc-http-connection
   #:engine-rpc-http-connection-input-stream
   #:engine-rpc-http-connection-output-stream
   #:engine-rpc-http-connection-close-function
   #:engine-rpc-http-connection-close
   #:engine-rpc-http-listener
   #:make-engine-rpc-http-listener
   #:make-engine-rpc-http-socket-listener
   #:engine-rpc-http-listener-endpoint
   #:engine-rpc-http-listener-accept-function
   #:engine-rpc-http-listener-close-function
   #:engine-rpc-http-listener-accept
   #:engine-rpc-http-listener-close
   #:engine-rpc-make-jwt-token
   #:rpc-http-handle-request
   #:rpc-http-handle-stream
   #:engine-rpc-handle-http-request-string
   #:engine-rpc-handle-http-stream
   #:engine-rpc-http-service-handle-stream
   #:engine-rpc-http-service-serve-listener))

(defpackage #:ethereum-lisp.websocket
  ;; TRANSPORT ONLY, and the short use-list is the point: nothing here knows
  ;; what a block is. The session is handed functions by the layer above.
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.strings)
  (:export
   #:+websocket-opcode-continuation+
   #:+websocket-opcode-text+
   #:+websocket-opcode-binary+
   #:+websocket-opcode-close+
   #:+websocket-opcode-ping+
   #:+websocket-opcode-pong+
   #:+websocket-default-max-message-bytes+
   #:websocket-protocol-error
   #:websocket-protocol-error-message
   #:websocket-protocol-error-status
   #:websocket-frame
   #:make-websocket-frame
   #:websocket-frame-fin-p
   #:websocket-frame-opcode
   #:websocket-frame-payload
   #:websocket-decode-frame
   #:websocket-encode-frame
   #:websocket-text-frame
   #:websocket-close-frame
   #:websocket-pong-frame
   #:websocket-unmask
   #:string-to-utf8-bytes
   #:utf8-bytes-to-string
   #:websocket-base64-encode
   #:websocket-accept-token
   #:websocket-header-value
   #:websocket-header-contains-token-p
   #:websocket-upgrade-request-p
   #:websocket-origin-allowed-p
   #:websocket-handshake-response
   #:websocket-request-path
   #:websocket-http-error
   #:websocket-connection
   #:make-websocket-connection
   #:websocket-connection-stream
   #:websocket-connection-closed-p
   #:websocket-send-text
   #:websocket-send-close
   #:websocket-handle-frame
   #:websocket-assemble-message
   #:websocket-take-frame
   #:websocket-pump))
