(defpackage #:ethereum-lisp.cli
  (:use #:cl
        #:ethereum-lisp
        #:ethereum-lisp.telemetry)
  (:import-from #:ethereum-lisp.types
                #:hash32=)
  (:import-from #:ethereum-lisp.txpool
                #:engine-payload-store-enable-txpool-database-change-tracking
                #:engine-payload-store-txpool-database-change-tracking-enabled-p
                #:engine-payload-store-clear-txpool-database-dirty-transaction-hashes
                #:engine-payload-store-pending-mining-transactions
                #:engine-payload-store-pooled-transaction
                #:engine-payload-store-pooled-transactions
                #:engine-select-mining-transactions)
  ;; The admin RPC namespace reads peering state through a backend of closures
  ;; the node builds; the struct itself belongs to the API layer.
  (:import-from #:ethereum-lisp.public-api
                #:make-admin-backend)
  ;; Gossiped transactions go through the same admission the public RPC uses.
  (:import-from #:ethereum-lisp.txpool.application
                #:make-txpool-admission-policy
                #:txpool-admit-transaction)
  (:import-from #:ethereum-lisp.node-store.persistence
                #:make-node-store-persistence-metadata
                #:node-store-persistence-metadata-role
                #:node-store-persistence-metadata-generation
                #:node-store-persistence-metadata-chain-id
                #:node-store-persistence-metadata-genesis-hash
                #:node-store-persistence-metadata-authority-id
                #:node-store-persistence-metadata-base-chain-generation
                #:node-store-read-persistence-metadata
                #:node-store-export-payload-candidate-to-kv
                #:node-store-export-forkchoice-to-kv
                #:node-store-export-to-kv
                #:node-store-export-txpool-records-to-kv
                #:node-store-import-txpool-records-from-kv
                #:node-store-restore-txpool-consistency)
  (:import-from #:ethereum-lisp.validation
                #:block-validation-fail
                #:storage-error
                #:storage-fail)
  (:export
   #:make-devnet-peer-table
   #:devnet-peer-table
   #:devnet-peer-table-count
   #:devnet-peer-table-entry
   #:devnet-peer-table-entries
   #:devnet-peer-table-max-peers
   #:devnet-peer-table-pending
   #:devnet-peer-table-self-id-hex
   #:devnet-peer-table-slot-verdict
   #:devnet-peer-table-reserve-slot
   #:devnet-peer-table-release-slot
   #:devnet-peer-table-inbound-verdict
   #:devnet-peer-table-admit
   #:devnet-peer-table-remove
   #:devnet-peer-table-snapshot
   #:devnet-peer-table-count-by-direction
   #:+devnet-dial-cooldown-seconds+
   #:+devnet-dial-backoff-ceiling-seconds+
   #:+devnet-dial-backoff-max-doublings+
   #:+devnet-max-active-dials+
   #:+devnet-dial-ratio+
   #:+devnet-dial-dynamic-candidate-limit+
   #:+devnet-dial-dynamic-forget-failures+
   #:devnet-dial-candidate
   #:make-devnet-dial-candidate
   #:devnet-dial-candidate-id-hex
   #:devnet-dial-candidate-enode
   #:devnet-dial-candidate-kind
   #:devnet-dial-candidate-state
   #:devnet-dial-candidate-failures
   #:devnet-dial-candidate-next-eligible-at
   #:devnet-dial-registry
   #:make-devnet-dial-registry
   #:devnet-dial-registry-candidate
   #:devnet-dial-registry-count
   #:devnet-dial-backoff-seconds
   #:devnet-dial-registry-put-static
   #:devnet-dial-registry-offer-dynamic
   #:devnet-dial-registry-dialing-count
   #:devnet-dial-free-slots
   #:devnet-dial-verdict
   #:devnet-dial-registry-plan
   #:devnet-dial-registry-claim-plan
   #:devnet-dial-registry-mark-dialing
   #:devnet-dial-registry-mark-connected
   #:devnet-dial-registry-mark-done
   #:devnet-dial-registry-expire
   #:devnet-dial-registry-snapshot
   #:devnet-peer-entry
   #:make-devnet-peer-entry
   #:devnet-peer-entry-id-hex
   #:devnet-peer-entry-direction
   #:devnet-peer-entry-remote-host
   #:devnet-peer-entry-remote-port
   #:devnet-peer-entry-eth-version
   #:devnet-peer-entry-client-id
   #:devnet-peer-entry-connected-at
   #:+devnet-default-max-peers+
   #:devnet-node-peer-table
   #:devnet-node-p2p-host
   #:devnet-node-p2p-port
   #:devnet-node-enode
   #:devnet-shutdown-controller-add-closeable
   #:devnet-shutdown-controller-remove-closeable
   #:devnet-start-p2p-listener-thread
   #:devnet-join-peer-sessions
   #:devnet-node
   #:devnet-endpoint-config
   #:make-devnet-endpoint-config
   #:devnet-txpool-policy
   #:make-devnet-txpool-policy
   #:make-devnet-node
   #:devnet-node-genesis-path
   #:devnet-node-store
   #:devnet-node-config
   #:devnet-node-genesis-block
   #:devnet-node-service
   #:devnet-node-public-service
   #:devnet-node-telemetry-sink
   #:devnet-node-jwt-secret-path
   #:devnet-node-log-path
   #:devnet-node-database-path
   #:devnet-node-pid-file-path
   #:devnet-node-prune-state-before
   #:devnet-shutdown-controller
   #:make-devnet-shutdown-controller
   #:devnet-shutdown-controller-requested-p
   #:devnet-shutdown-requested-p
   #:devnet-shutdown-request
   #:devnet-node-summary
   #:start-devnet-node-listeners
   #:start-devnet-node
   #:main))
