(defpackage #:ethereum-lisp.engine-payloads
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg)
  (:export
   #:executable-data
   #:executable-data-p
   #:make-executable-data
   #:executable-data-parent-hash
   #:executable-data-fee-recipient
   #:executable-data-state-root
   #:executable-data-receipts-root
   #:executable-data-logs-bloom
   #:executable-data-random
   #:executable-data-number
   #:executable-data-gas-limit
   #:executable-data-gas-used
   #:executable-data-timestamp
   #:executable-data-extra-data
   #:executable-data-base-fee-per-gas
   #:executable-data-block-hash
   #:executable-data-transactions
   #:executable-data-withdrawals
   #:executable-data-withdrawals-present-p
   #:executable-data-blob-gas-used
   #:executable-data-excess-blob-gas
   #:executable-data-slot-number
   #:executable-data-block-access-list
   #:execution-payload-envelope
   #:execution-payload-envelope-p
   #:make-execution-payload-envelope
   #:execution-payload-envelope-execution-payload
   #:execution-payload-envelope-block-value
   #:execution-payload-envelope-blobs-bundle
   #:execution-payload-envelope-requests
   #:execution-payload-envelope-override-p
   #:+payload-status-valid+
   #:+payload-status-invalid+
   #:+payload-status-syncing+
   #:+payload-status-accepted+
   #:+eth-protocol-version+
   #:payload-status
   #:payload-status-p
   #:make-payload-status
   #:payload-status-status
   #:payload-status-latest-valid-hash
   #:payload-status-validation-error
   #:payload-status-witness
   #:forkchoice-state
   #:forkchoice-state-p
   #:make-forkchoice-state
   #:forkchoice-state-head-block-hash
   #:forkchoice-state-safe-block-hash
   #:forkchoice-state-finalized-block-hash
   #:payload-attributes-v1
   #:payload-attributes-v1-p
   #:make-payload-attributes-v1
   #:payload-attributes-v1-timestamp
   #:payload-attributes-v1-prev-randao
   #:payload-attributes-v1-suggested-fee-recipient
   #:payload-attributes-v1-withdrawals
   #:payload-attributes-v1-withdrawals-present-p
   #:payload-attributes-v1-parent-beacon-root
   #:payload-attributes-v1-parent-beacon-root-present-p
   #:payload-attributes-v1-slot-number
   #:payload-attributes-v1-slot-number-present-p
   #:engine-prepared-payload
   #:engine-prepared-payload-p
   #:make-engine-prepared-payload
   #:engine-prepared-payload-payload-id
   #:engine-prepared-payload-version
   #:engine-prepared-payload-block
   #:engine-prepared-payload-blobs-bundle
   #:validate-engine-prepared-payload
   #:maybe-copy-bytes
   #:maybe-copy-withdrawals
   #:maybe-copy-requests
   #:maybe-copy-blob-sidecar
   #:block-to-executable-data
   #:executable-data-decoded-transactions
   #:executable-data-blob-versioned-hashes
   #:engine-new-payload-require-transaction-senders
   #:validate-executable-data-versioned-hashes
   #:executable-data-to-block-no-hash
   #:executable-data-to-block
   #:engine-new-payload-params-status
   #:engine-new-payload-version-status
   #:invalid-payload-status
   #:forkchoice-state-zero-head-status
   #:engine-payload-id
   #:engine-payload-id-v1
   #:engine-payload-id-with-transactions
   #:engine-build-empty-payload
   #:engine-build-empty-payload-v1))
