(defpackage #:ethereum-lisp.chain-config
  (:use #:cl #:ethereum-lisp.validation)
  (:export
   #:+blob-gas-per-blob+
   #:+target-blobs-per-block+
   #:+max-blobs-per-block+
   #:+osaka-target-blobs-per-block+
   #:+osaka-max-blobs-per-block+
   #:+bpo1-target-blobs-per-block+
   #:+bpo1-max-blobs-per-block+
   #:+bpo2-target-blobs-per-block+
   #:+bpo2-max-blobs-per-block+
   #:+bpo3-target-blobs-per-block+
   #:+bpo3-max-blobs-per-block+
   #:+bpo4-target-blobs-per-block+
   #:+bpo4-max-blobs-per-block+
   #:+blob-base-fee-update-fraction+
   #:+osaka-blob-base-fee-update-fraction+
   #:+bpo1-blob-base-fee-update-fraction+
   #:+bpo2-blob-base-fee-update-fraction+
   #:+bpo3-blob-base-fee-update-fraction+
   #:+bpo4-blob-base-fee-update-fraction+
   #:+max-contract-code-size+
   #:+amsterdam-max-contract-code-size+
   #:+transaction-gas-limit-cap-eip7825+
   #:+max-rlp-block-size-eip7934+
   #:+max-blobs-per-transaction-eip7594+
   #:chain-rules-max-blobs-per-transaction
   #:blob-schedule-entry
   #:make-blob-schedule-entry
   #:blob-schedule-entry-timestamp
   #:blob-schedule-entry-target-blobs
   #:blob-schedule-entry-max-blobs
   #:blob-schedule-entry-update-fraction
   #:chain-config
   #:make-chain-config
   #:chain-config-chain-id
   #:chain-config-homestead-block
   #:chain-config-dao-fork-block
   #:chain-config-dao-fork-support
   #:chain-config-eip150-block
   #:chain-config-eip155-block
   #:chain-config-eip158-block
   #:chain-config-byzantium-block
   #:chain-config-constantinople-block
   #:chain-config-petersburg-block
   #:chain-config-istanbul-block
   #:chain-config-muir-glacier-block
   #:chain-config-berlin-block
   #:chain-config-london-block
   #:chain-config-arrow-glacier-block
   #:chain-config-gray-glacier-block
   #:chain-config-shanghai-time
   #:chain-config-cancun-time
   #:chain-config-prague-time
   #:chain-config-osaka-time
   #:chain-config-bpo1-time
   #:chain-config-bpo2-time
   #:chain-config-bpo3-time
   #:chain-config-bpo4-time
   #:chain-config-bpo5-time
   #:chain-config-amsterdam-time
   #:chain-config-ubt-time
   #:chain-config-enable-ubt-at-genesis-p
   #:chain-config-terminal-total-difficulty
   #:chain-config-terminal-total-difficulty-passed
   #:chain-config-terminal-block-hash
   #:chain-config-terminal-block-number
   #:chain-config-merge-netsplit-block
   #:chain-config-deposit-contract-address
   #:chain-config-custom-blob-schedule
   #:fork-block-active-p
   #:fork-time-active-p
   #:chain-config-homestead-p
   #:chain-config-dao-fork-p
   #:chain-config-eip150-p
   #:chain-config-eip155-p
   #:chain-config-eip158-p
   #:chain-config-byzantium-p
   #:chain-config-constantinople-p
   #:chain-config-petersburg-p
   #:chain-config-istanbul-p
   #:chain-config-berlin-p
   #:chain-config-london-p
   #:chain-config-shanghai-p
   #:chain-config-cancun-p
   #:chain-config-prague-p
   #:chain-config-osaka-p
   #:chain-config-bpo1-p
   #:chain-config-bpo2-p
   #:chain-config-bpo3-p
   #:chain-config-bpo4-p
   #:chain-config-bpo5-p
   #:chain-config-amsterdam-p
   #:chain-config-ubt-p
   #:chain-config-ubt-genesis-p
   #:chain-config-block-fork-schedule
   #:chain-config-time-fork-schedule
   #:chain-config-expanded-blob-schedule-p
   #:chain-config-blob-schedule
   #:chain-config-rules
   #:chain-rules
   #:make-chain-rules
   #:chain-rules-chain-id
   #:chain-rules-homestead-p
   #:chain-rules-eip150-p
   #:chain-rules-eip155-p
   #:chain-rules-eip158-p
   #:chain-rules-byzantium-p
   #:chain-rules-constantinople-p
   #:chain-rules-petersburg-p
   #:chain-rules-istanbul-p
   #:chain-rules-berlin-p
   #:chain-rules-london-p
   #:chain-rules-shanghai-p
   #:chain-rules-cancun-p
   #:chain-rules-prague-p
   #:chain-rules-osaka-p
   #:chain-rules-bpo1-p
   #:chain-rules-bpo2-p
   #:chain-rules-bpo3-p
   #:chain-rules-bpo4-p
   #:chain-rules-bpo5-p
   #:chain-rules-amsterdam-p
   #:chain-rules-ubt-p
   #:chain-rules-blob-schedule-target-gas
   #:chain-rules-blob-schedule-max-gas
   #:chain-rules-blob-schedule-update-fraction
   #:chain-rules-expanded-blob-schedule-p
   #:chain-rules-blob-schedule
   #:chain-rules-initcode-metering-p
   #:chain-rules-code-prefix-restricted-p
   #:chain-rules-contract-code-size-limit
   #:chain-rules-contract-initcode-size-limit))

(defpackage #:ethereum-lisp.transactions
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config)
  (:export
   #:chain-rules-transaction-type-supported-p
   #:legacy-transaction
   #:make-legacy-transaction
   #:legacy-transaction-nonce
   #:legacy-transaction-gas-price
   #:legacy-transaction-gas-limit
   #:legacy-transaction-to
   #:legacy-transaction-value
   #:legacy-transaction-data
   #:legacy-transaction-v
   #:legacy-transaction-r
   #:legacy-transaction-s
   #:legacy-transaction-rlp
   #:legacy-transaction-from-rlp
   #:legacy-transaction-hash
   #:legacy-transaction-signing-payload
   #:legacy-transaction-signing-hash
   #:legacy-transaction-protected-p
   #:legacy-transaction-chain-id
   #:legacy-transaction-sender
   #:access-list-entry
   #:make-access-list-entry
   #:access-list-entry-address
   #:access-list-entry-storage-keys
   #:access-list-storage-key-count
   #:access-list-transaction
   #:make-access-list-transaction
   #:access-list-transaction-chain-id
   #:access-list-transaction-nonce
   #:access-list-transaction-gas-price
   #:access-list-transaction-gas-limit
   #:access-list-transaction-to
   #:access-list-transaction-value
   #:access-list-transaction-data
   #:access-list-transaction-access-list
   #:access-list-transaction-y-parity
   #:access-list-transaction-r
   #:access-list-transaction-s
   #:access-list-transaction-encoding
   #:access-list-transaction-from-rlp
   #:access-list-transaction-hash
   #:access-list-transaction-signing-payload
   #:access-list-transaction-signing-hash
   #:access-list-transaction-sender
   #:dynamic-fee-transaction
   #:make-dynamic-fee-transaction
   #:dynamic-fee-transaction-chain-id
   #:dynamic-fee-transaction-nonce
   #:dynamic-fee-transaction-max-priority-fee-per-gas
   #:dynamic-fee-transaction-max-fee-per-gas
   #:dynamic-fee-transaction-gas-limit
   #:dynamic-fee-transaction-to
   #:dynamic-fee-transaction-value
   #:dynamic-fee-transaction-data
   #:dynamic-fee-transaction-access-list
   #:dynamic-fee-transaction-y-parity
   #:dynamic-fee-transaction-r
   #:dynamic-fee-transaction-s
   #:dynamic-fee-transaction-encoding
   #:dynamic-fee-transaction-from-rlp
   #:dynamic-fee-transaction-hash
   #:dynamic-fee-transaction-signing-payload
   #:dynamic-fee-transaction-signing-hash
   #:dynamic-fee-transaction-sender
   #:blob-transaction
   #:make-blob-transaction
   #:blob-transaction-chain-id
   #:blob-transaction-nonce
   #:blob-transaction-gas-limit
   #:blob-transaction-to
   #:blob-transaction-value
   #:blob-transaction-data
   #:blob-transaction-access-list
   #:blob-transaction-y-parity
   #:blob-transaction-r
   #:blob-transaction-s
   #:blob-transaction-max-priority-fee-per-gas
   #:blob-transaction-max-fee-per-gas
   #:blob-transaction-blob-versioned-hashes
   #:blob-transaction-max-fee-per-blob-gas
   #:blob-transaction-encoding
   #:blob-transaction-from-rlp
   #:blob-transaction-hash
   #:blob-transaction-signing-hash
   #:blob-transaction-sender
   #:blob-sidecar
   #:make-blob-sidecar
   #:blob-sidecar-blobs
   #:blob-sidecar-commitments
   #:blob-sidecar-proofs
   #:blob-sidecar-versioned-hashes
   #:blob-versioned-hash-bytes
   #:set-code-authorization
   #:make-set-code-authorization
   #:set-code-authorization-chain-id
   #:set-code-authorization-address
   #:set-code-authorization-nonce
   #:set-code-authorization-y-parity
   #:set-code-authorization-r
   #:set-code-authorization-s
   #:set-code-authorization-from-rlp-object
   #:set-code-authorization-signing-hash
   #:set-code-authorization-authority
   #:set-code-delegation-code
   #:set-code-delegation-target
   #:set-code-transaction
   #:make-set-code-transaction
   #:set-code-transaction-chain-id
   #:set-code-transaction-nonce
   #:set-code-transaction-max-priority-fee-per-gas
   #:set-code-transaction-max-fee-per-gas
   #:set-code-transaction-gas-limit
   #:set-code-transaction-to
   #:set-code-transaction-value
   #:set-code-transaction-data
   #:set-code-transaction-access-list
   #:set-code-transaction-authorization-list
   #:set-code-transaction-y-parity
   #:set-code-transaction-r
   #:set-code-transaction-s
   #:set-code-transaction-encoding
   #:set-code-transaction-from-rlp
   #:set-code-transaction-hash
   #:set-code-transaction-signing-hash
   #:set-code-transaction-sender
   #:transaction-encoding
   #:transaction-from-encoding
   #:transaction-hash
   #:transaction-sender
   #:transaction-nonce
   #:transaction-gas-limit
   #:transaction-to
   #:transaction-recipient-bytes
   #:transaction-value
   #:transaction-data
   #:transaction-access-list
   #:transaction-authorization-list
   #:transaction-type
   #:validate-transaction-type-for-config
   #:transaction-blob-versioned-hashes
   #:transaction-blob-gas-used
   #:transaction-max-priority-fee-per-gas
   #:transaction-max-fee-per-gas
   #:validate-1559-transaction-fees
   #:transaction-effective-gas-price
   #:transaction-priority-fee-per-gas))
