(in-package #:ethereum-lisp.evm.internal)

(defmacro evm-comparison (machine form-of-left-right)
  "Pop LEFT and RIGHT, push 1 when FORM-OF-LEFT-RIGHT is true, else 0."
  `(let* ((left (evm-stack-pop ,machine))
          (right (evm-stack-pop ,machine)))
     (evm-stack-push-word ,machine (if ,form-of-left-right 1 0))))

(defun execute-arithmetic-opcode (machine opcode)
  "Execute arithmetic, comparison, bitwise, and KECCAK256 opcodes."
  (declare (type evm-machine machine) (type (unsigned-byte 8) opcode))
  (with-evm-machine-state (machine)
    (let ((op opcode))
      (cond
        ((= op #x00)
         (halt-evm-machine machine :stopped))
        ((= op #x01) (evm-machine-apply-binary machine #'+) (incf pc))
        ((= op #x02) (evm-machine-apply-binary machine #'*) (incf pc))
        ((= op #x03) (evm-machine-apply-binary machine #'-) (incf pc))
        ((= op #x04)
         (evm-machine-apply-binary machine (lambda (a b) (if (zerop b) 0 (floor a b))))
         (incf pc))
        ((= op #x05)
         (evm-machine-apply-binary machine #'signed-divide-word)
         (incf pc))
        ((= op #x06)
         (evm-machine-apply-binary machine (lambda (a b) (if (zerop b) 0 (mod a b))))
         (incf pc))
        ((= op #x07)
         (evm-machine-apply-binary machine #'signed-mod-word)
         (incf pc))
        ((= op #x08)
         (let* ((a (evm-stack-pop machine))
                (b (evm-stack-pop machine))
                (modulus (evm-stack-pop machine)))
           (evm-stack-push machine
                           (if (zerop modulus) 0 (mod (+ a b) modulus))))
         (incf pc))
        ((= op #x09)
         (let* ((a (evm-stack-pop machine))
                (b (evm-stack-pop machine))
                (modulus (evm-stack-pop machine)))
           (evm-stack-push machine
                           (if (zerop modulus) 0 (mod (* a b) modulus))))
         (incf pc))
        ((= op #x0a)
         (let* ((base (evm-stack-pop machine))
                (exponent (evm-stack-pop machine)))
           (evm-machine-charge-gas machine
            (* (exp-byte-gas
                (and context (evm-context-chain-rules context)))
               (exp-byte-count exponent)))
           (evm-stack-push machine (modexp-word base exponent)))
         (incf pc))
        ((= op #x0b)
         (evm-machine-apply-binary machine #'signextend-word)
         (incf pc))
        ((= op #x10) (evm-comparison machine (< left right)) (incf pc))
        ((= op #x11) (evm-comparison machine (> left right)) (incf pc))
        ((= op #x12)
         (evm-comparison machine (< (signed-word left) (signed-word right)))
         (incf pc))
        ((= op #x13)
         (evm-comparison machine (> (signed-word left) (signed-word right)))
         (incf pc))
        ((= op #x14) (evm-comparison machine (= left right)) (incf pc))
        ((= op #x15)
         (let ((a (evm-stack-pop machine)))
           (evm-stack-push-word machine (if (zerop a) 1 0)))
         (incf pc))
        ((= op #x16) (evm-machine-apply-binary machine #'logand) (incf pc))
        ((= op #x17) (evm-machine-apply-binary machine #'logior) (incf pc))
        ((= op #x18) (evm-machine-apply-binary machine #'logxor) (incf pc))
        ((= op #x19)
         (let ((a (evm-stack-pop machine)))
           (evm-stack-push machine (logxor a (1- +word-modulus+))))
         (incf pc))
        ((= op #x1a)
         (evm-machine-apply-binary machine #'byte-op)
         (incf pc))
        ((= op #x1b)
         (require-context-fork context
                               #'chain-rules-constantinople-p
                               "Constantinople" "SHL" pc)
         (evm-machine-apply-binary machine (lambda (shift value)
                   (if (>= shift 256) 0 (word (ash value shift)))))
         (incf pc))
        ((= op #x1c)
         (require-context-fork context
                               #'chain-rules-constantinople-p
                               "Constantinople" "SHR" pc)
         (evm-machine-apply-binary machine (lambda (shift value)
                   (if (>= shift 256) 0 (ash value (- shift)))))
         (incf pc))
        ((= op #x1d)
         (require-context-fork context
                               #'chain-rules-constantinople-p
                               "Constantinople" "SAR" pc)
         (evm-machine-apply-binary machine #'arithmetic-shift-right-word)
         (incf pc))
        ((= op #x1e)
         (require-context-fork context
                               #'chain-rules-osaka-p
                               "Osaka" "CLZ" pc)
         (let ((a (evm-stack-pop machine)))
           (evm-stack-push machine (- 256 (integer-length a))))
         (incf pc))
        ((= op #x20)
         (let* ((offset (evm-stack-pop machine))
                (size (evm-stack-pop machine)))
           (evm-machine-charge-gas machine
            (+ (memory-expansion-gas memory offset size)
               (* +keccak256-word-gas+
                  (memory-word-count size))))
           (setf memory (ensure-memory-size memory (+ offset size)))
           (evm-stack-push
            machine
            (bytes-to-integer
             (keccak-256 (memory-slice memory offset size)))))
         (incf pc))
        (t
         (fail "Unsupported EVM opcode 0x~2,'0X at pc ~D" op pc))))))
