(defparameter *ethereum-lisp-script-root*
  (merge-pathnames "../" (or *load-truename* *default-pathname-defaults*)))

(defun ethereum-lisp-script-arguments ()
  #+sbcl
  (let ((args (cdr sb-ext:*posix-argv*)))
    (when (and args (string= (first args) "--"))
      (setf args (rest args)))
    args)
  #-sbcl
  nil)

(defun ethereum-lisp-script-load-file (relative-path)
  (load (merge-pathnames relative-path *ethereum-lisp-script-root*)))

(require :asdf)

(dolist (relative-path
         '("src/packages.lisp"
           "src/bytes.lisp"
           "src/hex.lisp"
           "src/database.lisp"
           "src/telemetry.lisp"
           "src/types.lisp"
           "src/rlp.lisp"
           "src/crypto-constants.lisp"
           "src/crypto-words.lisp"
           "src/crypto-keccak.lisp"
           "src/crypto-sha256.lisp"
           "src/crypto-ripemd160.lisp"
           "src/crypto-kzg.lisp"
           "src/crypto-math.lisp"
           "src/crypto-secp256k1.lisp"
           "src/crypto-empty-hashes.lisp"
           "src/crypto.lisp"
           "src/trie-encoding.lisp"
           "src/trie.lisp"
           "src/chain-config.lisp"
           "src/genesis-types.lisp"
           "src/genesis-object-fields.lisp"
           "src/genesis-alloc.lisp"
           "src/genesis-json-read.lisp"
           "src/genesis-json-write.lisp"
           "src/genesis-chain-config.lisp"
           "src/genesis-io.lisp"
           "src/genesis.lisp"
           "src/core-constants.lisp"
           "src/accounts.lisp"
           "src/transactions-legacy.lisp"
           "src/transactions-access-list.lisp"
           "src/transactions-dynamic-fee.lisp"
           "src/transactions-blob.lisp"
           "src/transactions-set-code.lisp"
           "src/transactions.lisp"
           "src/receipts.lisp"
           "src/txpool-types.lisp"
           "src/blocks.lisp"
           "src/consensus-validation.lisp"
           "src/block-access-list.lisp"
           "src/genesis-block.lisp"
           "src/kzg.lisp"
           "src/engine-payload-types.lisp"
           "src/engine-payload-codecs.lisp"
           "src/engine-payload-blocks.lisp"
           "src/engine-payload-validation.lisp"
           "src/engine-payload-build.lisp"
           "src/engine-payloads.lisp"
           "src/chain-store-types.lisp"
           "src/chain-store-copy.lisp"
           "src/chain-store-filters.lisp"
           "src/chain-store-cache.lisp"
           "src/chain-store-memory.lisp"
           "src/chain-store-state.lisp"
           "src/chain-store-canonical.lisp"
           "src/txpool-index.lisp"
           "src/txpool.lisp"
           "src/txpool-views.lisp"
           "src/txpool-promotion.lisp"
           "src/txpool-cleanup.lisp"
           "src/chain-store-export.lisp"
           "src/chain-store-persistence-core.lisp"
           "src/chain-store-persistence-receipts.lisp"
           "src/chain-store-persistence-state.lisp"
           "src/chain-store-persistence-locations.lisp"
           "src/chain-store-persistence-txpool.lisp"
           "src/chain-store-persistence-side-data.lisp"
           "src/chain-store-persistence-blobs.lisp"
           "src/chain-store-persistence-prepared-payloads.lisp"
           "src/chain-store-persistence.lisp"
           "src/block-validation-forks.lisp"
           "src/block-validation-header.lisp"
           "src/block-validation-body.lisp"
           "src/block-validation-roots.lisp"
           "src/block-validation.lisp"
           "src/engine-payload-status.lisp"
           "src/engine-rpc-protocol.lisp"
           "src/engine-rpc-codecs.lisp"
           "src/engine-rpc-new-payload.lisp"
           "src/engine-rpc-errors.lisp"
           "src/engine-rpc-payloads.lisp"
           "src/engine-rpc-blobs.lisp"
           "src/engine-rpc-forkchoice.lisp"
           "src/engine-rpc.lisp"
           "src/public-rpc-params.lisp"
           "src/public-rpc-core.lisp"
           "src/public-rpc-state-queries.lisp"
           "src/public-rpc-state-proofs.lisp"
           "src/public-rpc-call-objects.lisp"
           "src/public-rpc-gas.lisp"
           "src/public-rpc-access-lists.lisp"
           "src/public-rpc-state.lisp"
           "src/public-rpc-transaction-objects.lisp"
           "src/public-rpc-transactions.lisp"
           "src/public-rpc-txpool.lisp"
           "src/public-rpc-receipts.lisp"
           "src/public-rpc-blocks.lisp"
           "src/public-rpc-log-filters.lisp"
           "src/public-rpc-filter-changes.lisp"
           "src/public-rpc-filter-handlers.lisp"
           "src/public-rpc.lisp"
           "src/engine-rpc-http-auth.lisp"
           "src/engine-rpc-http-wire.lisp"
           "src/engine-rpc-http.lisp"
           "src/engine-rpc-http-service.lisp"
           "src/state-types.lisp"
           "src/state-db.lisp"
           "src/state-roots.lisp"
           "src/state-proofs.lisp"
           "src/state-ranges.lisp"
           "src/state-genesis.lisp"
           "src/state-transactions.lisp"
           "src/state.lisp"
           "src/evm-types.lisp"
           "src/evm-runtime-base.lisp"
           "src/evm-runtime-memory.lisp"
           "src/evm-runtime-opcodes.lisp"
           "src/evm-runtime-conversions.lisp"
           "src/evm-runtime-access.lisp"
           "src/evm-runtime-state.lisp"
           "src/evm-runtime-create.lisp"
           "src/evm-runtime-gas.lisp"
           "src/evm-runtime-block.lisp"
           "src/evm-runtime.lisp"
           "src/evm-precompiles-utils.lisp"
           "src/evm-precompiles-modexp.lisp"
           "src/evm-precompiles-bn254-base.lisp"
           "src/evm-precompiles-bn254-g2.lisp"
           "src/evm-precompiles-bn254-fields.lisp"
           "src/evm-precompiles-bn254-pairing.lisp"
           "src/evm-precompiles-kzg.lisp"
           "src/evm-precompiles-blake2f.lisp"
           "src/evm-precompiles-dispatch.lisp"
           "src/evm-precompiles.lisp"
           "src/evm.lisp"
           "src/execution-constants.lisp"
           "src/execution-state.lisp"
           "src/execution-rewards.lisp"
           "src/execution-gas.lisp"
           "src/execution-validation.lisp"
           "src/execution-set-code.lisp"
           "src/execution-accounting.lisp"
           "src/execution-access.lisp"
           "src/execution-rules.lisp"
           "src/execution-context.lisp"
           "src/execution-call-simulation.lisp"
           "src/execution-apply-contract.lisp"
           "src/execution-signatures.lisp"
           "src/execution-apply-message.lisp"
           "src/execution-message-lists.lisp"
           "src/execution-message.lisp"
           "src/execution-block-validation.lisp"
           "src/execution.lisp"
           "src/cli-types.lisp"
           "src/cli-files.lisp"
           "src/cli-devnet-node.lisp"
           "src/cli-devnet-runtime.lisp"
           "src/cli-devnet-summary.lisp"
           "src/cli-devnet-service.lisp"
           "src/cli-devnet.lisp"
           "src/cli-args.lisp"
           "src/cli-config.lisp"
           "src/cli-parsers.lisp"
           "src/cli-options.lisp"
           "src/cli-output.lisp"
           "src/cli-telemetry.lisp"
           "src/cli-init.lisp"
           "src/cli.lisp"))
  (ethereum-lisp-script-load-file relative-path))

(let ((exit-code (ethereum-lisp.cli:main (ethereum-lisp-script-arguments))))
  #+sbcl
  (sb-ext:exit :code exit-code)
  #-sbcl
  (uiop:quit exit-code))
