(in-package #:ethereum-lisp.crypto)

(defun lane-index (x y)
  (+ x (* 5 y)))

(defun keccak-f1600 (state)
  (dotimes (round 24 state)
    (let ((c (make-array 5))
          (d (make-array 5))
          (b (make-array 25)))
      (dotimes (x 5)
        (setf (aref c x)
              (u64 (logxor (aref state (lane-index x 0))
                           (aref state (lane-index x 1))
                           (aref state (lane-index x 2))
                           (aref state (lane-index x 3))
                           (aref state (lane-index x 4))))))
      (dotimes (x 5)
        (setf (aref d x)
              (u64 (logxor (aref c (mod (1- x) 5))
                           (rotl64 (aref c (mod (1+ x) 5)) 1)))))
      (dotimes (x 5)
        (dotimes (y 5)
          (let ((index (lane-index x y)))
            (setf (aref state index)
                  (u64 (logxor (aref state index) (aref d x)))))))
      (dotimes (x 5)
        (dotimes (y 5)
          (let* ((index (lane-index x y))
                 (new-x y)
                 (new-y (mod (+ (* 2 x) (* 3 y)) 5)))
            (setf (aref b (lane-index new-x new-y))
                  (rotl64 (aref state index)
                          (aref +keccak-rotation-offsets+ index))))))
      (dotimes (x 5)
        (dotimes (y 5)
          (setf (aref state (lane-index x y))
                (u64 (logxor (aref b (lane-index x y))
                             (logand (lognot (aref b (lane-index (mod (1+ x) 5) y)))
                                     (aref b (lane-index (mod (+ x 2) 5) y))))))))
      (setf (aref state 0)
            (u64 (logxor (aref state 0)
                         (aref +keccak-round-constants+ round)))))))

(defun absorb-block (state block)
  (dotimes (lane (/ +keccak-256-rate+ 8))
    (let ((offset (* lane 8)))
      (setf (aref state lane)
            (u64 (logxor (aref state lane)
                         (load-little-endian-u64 block offset))))))
  (keccak-f1600 state))

(defun keccak-256 (&rest chunks)
  "Return Ethereum legacy Keccak-256 of all byte CHUNKS concatenated."
  (let ((state (make-array 25 :initial-element 0))
        (block (make-byte-vector +keccak-256-rate+))
        (offset 0))
    (labels ((absorb-byte (byte)
               (setf (aref block offset) byte)
               (incf offset)
               (when (= offset +keccak-256-rate+)
                 (absorb-block state block)
                 (fill block 0)
                 (setf offset 0))))
      (dolist (chunk chunks)
        (loop for byte across (ensure-byte-vector chunk)
              do (absorb-byte byte)))
      (setf (aref block offset) (logxor (aref block offset) #x01)
            (aref block (1- +keccak-256-rate+))
            (logxor (aref block (1- +keccak-256-rate+)) #x80))
      (absorb-block state block))
    (let ((out (make-byte-vector 32)))
      (dotimes (lane 4)
        (store-little-endian-u64 (aref state lane) out (* lane 8)))
      out)))

(defun keccak-256-hash (&rest chunks)
  (make-hash32 (apply #'keccak-256 chunks)))

(defun keccak-256-hex (&rest chunks)
  (bytes-to-hex (apply #'keccak-256 chunks)))

(defparameter +empty-code-hash+ (keccak-256-hash #()))
(defparameter +empty-trie-hash+ (keccak-256-hash #(128)))
