(in-package #:ethereum-lisp.evm)

(defun ensure-precompile-upfront-gas (address input rules child-gas-limit)
  (case (address-to-word address)
    (5
     (when (active-precompile-address-number-p 5 rules)
       (let ((required-gas (modexp-precompile-required-gas input)))
         (when (> required-gas child-gas-limit)
           (fail "Precompile out of gas")))))
    (9
     (when (active-precompile-address-number-p 9 rules)
       (let ((required-gas (blake2f-precompile-required-gas input)))
         (when (and required-gas (> required-gas child-gas-limit))
           (fail "Precompile out of gas")))))))

(defun all-zero-bytes-p (bytes start end)
  (loop for i from start below end
        always (zerop (aref bytes i))))

(defun run-ecrecover-precompile (input)
  (let* ((padded (padded-data-slice input 0 128))
         (v-byte (aref padded 63))
         (v (- v-byte 27))
         (r (bytes-to-integer (subseq padded 64 96)))
         (s (bytes-to-integer (subseq padded 96 128))))
    (let ((address
            (and (all-zero-bytes-p padded 32 63)
                 (secp256k1-recover-address (subseq padded 0 32) v r s))))
      (if address
          (let ((output (make-byte-vector 32)))
            (replace output (address-bytes address) :start1 12)
            (values output +ecrecover-gas+))
          (values (make-byte-vector 0) +ecrecover-gas+)))))

(defun precompile-word-count (input)
  (ceiling (length (ensure-byte-vector input)) 32))

(defun run-precompile (address input &optional rules)
  (let ((input (ensure-byte-vector input)))
    (case (address-to-word address)
      (1 (if (active-precompile-address-number-p 1 rules)
             (multiple-value-bind (output gas) (run-ecrecover-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (2 (if (active-precompile-address-number-p 2 rules)
             (values (sha256 input)
                     (+ +sha256-base-gas+
                        (* +sha256-word-gas+ (precompile-word-count input)))
                     t)
             (values nil 0 nil)))
      (3 (if (active-precompile-address-number-p 3 rules)
             (let ((output (make-byte-vector 32)))
               (replace output (ripemd160 input) :start1 12)
               (values output
                       (+ +ripemd160-base-gas+
                          (* +ripemd160-word-gas+
                             (precompile-word-count input)))
                       t))
             (values nil 0 nil)))
      (5 (if (active-precompile-address-number-p 5 rules)
             (multiple-value-bind (output gas) (run-modexp-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (6 (if (active-precompile-address-number-p 6 rules)
             (multiple-value-bind (output gas) (run-bn254-add-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (7 (if (active-precompile-address-number-p 7 rules)
             (multiple-value-bind (output gas) (run-bn254-mul-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (8 (if (active-precompile-address-number-p 8 rules)
             (multiple-value-bind (output gas)
                 (run-bn254-pairing-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (9 (if (active-precompile-address-number-p 9 rules)
             (multiple-value-bind (output gas) (run-blake2f-precompile input)
               (values output gas t))
             (values nil 0 nil)))
      (10 (if (active-precompile-address-number-p 10 rules)
              (multiple-value-bind (output gas)
                  (run-kzg-point-evaluation-precompile input)
                (values output gas t))
              (values nil 0 nil)))
      (4 (if (active-precompile-address-number-p 4 rules)
             (values (subseq input 0)
                     (+ +identity-base-gas+
                        (* +identity-word-gas+ (precompile-word-count input)))
                     t)
             (values nil 0 nil)))
      (otherwise (values nil 0 nil)))))
