(in-package #:ethereum-lisp.json)

(defun json-whitespace-p (char)
  (member char '(#\Space #\Tab #\Newline #\Return)))

(defun json-hex-value (char)
  (cond
    ((char<= #\0 char #\9) (- (char-code char) (char-code #\0)))
    ((char<= #\a char #\f) (+ 10 (- (char-code char) (char-code #\a))))
    ((char<= #\A char #\F) (+ 10 (- (char-code char) (char-code #\A))))
    (t nil)))

(defun json-parse-number (text)
  (handler-case
      (multiple-value-bind (value end) (read-from-string text)
        (unless (and (= end (length text)) (realp value))
          (data-decoding-fail "Invalid JSON number"))
        value)
    (error ()
      (data-decoding-fail "Invalid JSON number"))))

(defun parse-json (string &key preserve-empty-arrays preserve-types)
  (check-type string string)
  (let ((position 0)
        (length (length string)))
    (labels
        ((fail (control &rest args)
           (apply #'data-decoding-fail
                  (concatenate 'string "Invalid JSON at byte ~D: " control)
                  position args))
         (peek ()
           (when (< position length)
             (char string position)))
         (consume ()
           (prog1 (peek)
             (incf position)))
         (skip-whitespace ()
           (loop while (and (peek) (json-whitespace-p (peek)))
                 do (incf position)))
         (expect (char)
           (unless (and (peek) (char= (peek) char))
             (fail "expected ~S" char))
           (incf position))
         (parse-unicode-code-unit ()
           (let ((code 0))
             (dotimes (index 4)
               (declare (ignore index))
               (let ((digit (and (peek)
                                 (json-hex-value (consume)))))
                 (unless digit
                   (fail "invalid unicode escape"))
                 (setf code (+ (* code 16) digit))))
             code))
         (parse-unicode-character ()
           (let ((code (parse-unicode-code-unit)))
             (cond
               ((<= #xd800 code #xdbff)
                (unless (and (peek) (char= (consume) #\\)
                             (peek) (char= (consume) #\u))
                  (fail "high surrogate must be followed by a low surrogate"))
                (let ((low (parse-unicode-code-unit)))
                  (unless (<= #xdc00 low #xdfff)
                    (fail "invalid low surrogate"))
                  (or (code-char
                       (+ #x10000
                          (ash (- code #xd800) 10)
                          (- low #xdc00)))
                      (fail "invalid unicode code point"))))
               ((<= #xdc00 code #xdfff)
                (fail "unexpected low surrogate"))
               (t
                (or (code-char code)
                    (fail "invalid unicode code point"))))))
         (parse-literal (literal value)
           (let ((end (+ position (length literal))))
             (unless (and (<= end length)
                          (string= string literal :start1 position :end1 end))
               (fail "expected ~A" literal))
             (setf position end)
             value))
         (parse-string ()
           (expect #\")
           (let ((chars '()))
             (loop
               (unless (peek)
                 (fail "unterminated string"))
               (let ((char (consume)))
                 (cond
                   ((char= char #\")
                    (return (coerce (nreverse chars) 'string)))
                   ((char= char #\\)
                    (unless (peek)
                      (fail "unterminated escape"))
                    (let ((escape (consume)))
                      (push
                       (case escape
                         (#\" #\")
                         (#\\ #\\)
                         (#\/ #\/)
                         (#\b #\Backspace)
                         (#\f #\Page)
                         (#\n #\Newline)
                         (#\r #\Return)
                         (#\t #\Tab)
                         (#\u (parse-unicode-character))
                         (otherwise
                          (fail "invalid string escape ~S" escape)))
                       chars)))
                   ((< (char-code char) #x20)
                    (fail "control character in string"))
                   (t (push char chars)))))))
         (parse-number ()
           (let ((start position))
             (when (and (peek) (char= (peek) #\-))
               (incf position))
             (unless (and (peek) (digit-char-p (peek)))
               (fail "expected digit"))
             (if (char= (peek) #\0)
                 (incf position)
                 (loop while (and (peek) (digit-char-p (peek)))
                       do (incf position)))
             (when (and (peek) (char= (peek) #\.))
               (incf position)
               (unless (and (peek) (digit-char-p (peek)))
                 (fail "expected fractional digit"))
               (loop while (and (peek) (digit-char-p (peek)))
                     do (incf position)))
             (when (and (peek) (member (peek) '(#\e #\E)))
               (incf position)
               (when (and (peek) (member (peek) '(#\+ #\-)))
                 (incf position))
               (unless (and (peek) (digit-char-p (peek)))
                 (fail "expected exponent digit"))
               (loop while (and (peek) (digit-char-p (peek)))
                     do (incf position)))
             (json-parse-number (subseq string start position))))
         (parse-array ()
           (expect #\[)
           (skip-whitespace)
           (let ((items '()))
             (when (and (peek) (char= (peek) #\]))
               (incf position)
               (return-from parse-array
                 (if (or preserve-types preserve-empty-arrays)
                     (make-array 0)
                     '())))
             (loop
               (push (parse-value) items)
               (skip-whitespace)
               (cond
                 ((and (peek) (char= (peek) #\,))
                  (incf position)
                  (skip-whitespace))
                 ((and (peek) (char= (peek) #\]))
                  (incf position)
                  (return (nreverse items)))
                 (t (fail "expected comma or closing array"))))))
         (parse-object ()
           (expect #\{)
           (skip-whitespace)
           (let ((entries '()))
             (when (and (peek) (char= (peek) #\}))
               (incf position)
               (return-from parse-object
                 (if preserve-types +json-empty-object+ '())))
             (loop
               (unless (and (peek) (char= (peek) #\"))
                 (fail "expected object key"))
               (let ((key (parse-string)))
                 (skip-whitespace)
                 (expect #\:)
                 (skip-whitespace)
                 (push (cons key (parse-value)) entries))
               (skip-whitespace)
               (cond
                 ((and (peek) (char= (peek) #\,))
                  (incf position)
                  (skip-whitespace))
                 ((and (peek) (char= (peek) #\}))
                  (incf position)
                  (return (nreverse entries)))
                 (t (fail "expected comma or closing object"))))))
         (parse-value ()
           (skip-whitespace)
           (case (peek)
             (#\{ (parse-object))
             (#\[ (parse-array))
             (#\" (parse-string))
             (#\t (parse-literal "true" t))
             (#\f (parse-literal "false"
                                 (if preserve-types +json-false+ nil)))
             (#\n (parse-literal "null"
                                 (if preserve-types +json-null+ nil)))
             ((#\- #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9)
              (parse-number))
             (otherwise (fail "unexpected character")))))
      (let ((value (parse-value)))
        (skip-whitespace)
        (when (peek)
          (fail "trailing data"))
        value))))

(defun json-object-p (value)
  (or (json-empty-object-p value)
      (and (consp value)
           (every (lambda (entry)
                    (and (consp entry)
                         (or (stringp (car entry))
                             (symbolp (car entry)))))
                  value))))

(defun json-empty-array-p (value)
  (and (vectorp value)
       (not (stringp value))
       (zerop (length value))))

(defun json-array-p (value)
  (or (listp value)
      (json-empty-array-p value)))

(defun json-array-values (value)
  (if (json-empty-array-p value)
      '()
      value))
