(defpackage #:ethereum-lisp.txpool.application
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool)
  (:export
   #:txpool-admission-policy
   #:make-txpool-admission-policy
   #:txpool-admission-policy-allow-unprotected-transactions-p
   #:txpool-admission-policy-price-limit
   #:txpool-admission-policy-price-bump-percent
   #:txpool-admission-policy-account-slot-limit
   #:txpool-admission-policy-global-slot-limit
   #:txpool-admission-policy-account-queue-limit
   #:txpool-admission-policy-global-queue-limit
   #:txpool-admission-policy-local-addresses
   #:txpool-admission-policy-no-local-exemptions-p
   #:txpool-local-transaction-p
   #:txpool-local-transaction-predicate
   #:txpool-admit-transaction))

(defpackage #:ethereum-lisp.engine-api
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.strings
        #:ethereum-lisp.types
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.node-store
        #:ethereum-lisp.txpool
        #:ethereum-lisp.canonical-chain
        #:ethereum-lisp.engine
        #:ethereum-lisp.execution
        #:ethereum-lisp.execution-service)
  (:export
   #:+engine-rpc-capabilities+
   #:engine-rpc-capabilities
   #:+engine-rpc-client-version+
   #:engine-rpc-client-version
   #:engine-rpc-transition-configuration-object
   #:engine-rpc-executable-data-from-object
   #:engine-rpc-executable-data-object
   #:engine-rpc-withdrawal-object
   #:engine-rpc-payload-status-object
   #:engine-rpc-forkchoice-state-from-object
   #:engine-rpc-forkchoice-response-object
   #:engine-rpc-handle-get-payload-v1
   #:engine-rpc-handle-forkchoice-updated-v1
   #:engine-rpc-engine-method-p
   #:engine-rpc-public-method-p
   #:engine-rpc-any-method-p
   #:engine-rpc-error
   #:engine-rpc-error-code
   #:engine-rpc-error-message
   #:engine-rpc-handle-engine-method))

(defpackage #:ethereum-lisp.public-api
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.genesis
        #:ethereum-lisp.accounts
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store.state
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool
        #:ethereum-lisp.state
        #:ethereum-lisp.state-proof-json
        #:ethereum-lisp.evm
        #:ethereum-lisp.execution
        #:ethereum-lisp.execution-service
        #:ethereum-lisp.txpool.application
        #:ethereum-lisp.engine-api)
  (:export
   #:engine-rpc-handle-public-method))

(defpackage #:ethereum-lisp.rpc
  (:use #:cl
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.json-rpc
        #:ethereum-lisp.engine-api
        #:ethereum-lisp.public-api)
  (:export
   #:rpc-context
   #:make-rpc-context
   #:rpc-context-store
   #:rpc-context-config
   #:rpc-context-import-function
   #:rpc-context-new-payload-persistence-function
   #:rpc-context-network-id
   #:rpc-context-coinbase
   #:rpc-context-allowed-method-p
   #:rpc-context-rebind
   #:rpc-context-with-txpool-now
   #:rpc-handle-request
   #:rpc-handle-request-value
   #:rpc-handle-request-string
   #:rpc-handle-request-json
   #:engine-rpc-handle-request
   #:engine-rpc-handle-request-value
   #:engine-rpc-handle-request-string
   #:engine-rpc-handle-request-json))

(defpackage #:ethereum-lisp.rpc-http
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.strings
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.node-state
        #:ethereum-lisp.engine-api
        #:ethereum-lisp.execution-service
        #:ethereum-lisp.rpc)
  (:export
   #:+engine-rpc-http-accepted-content-types+
   #:engine-rpc-http-accepted-content-type-p
   #:+engine-rpc-default-http-host+
   #:+engine-rpc-default-http-port+
   #:+engine-rpc-jwt-expiry-seconds+
   #:engine-rpc-http-service
   #:make-engine-rpc-http-service
   #:engine-rpc-http-service-host
   #:engine-rpc-http-service-port
   #:engine-rpc-http-service-store
   #:engine-rpc-http-service-config
   #:engine-rpc-http-service-jwt-secret
   #:engine-rpc-http-service-now-provider
   #:engine-rpc-http-service-import-function
   #:engine-rpc-http-service-new-payload-persistence-function
   #:engine-rpc-http-service-telemetry-sink
   #:engine-rpc-http-service-allowed-method-p
   #:engine-rpc-http-service-network-id
   #:engine-rpc-http-service-coinbase
   #:engine-rpc-http-service-rpc-context
   #:engine-rpc-http-service-rpc-prefix
   #:engine-rpc-http-service-endpoint
   #:engine-rpc-http-connection
   #:make-engine-rpc-http-connection
   #:engine-rpc-http-connection-input-stream
   #:engine-rpc-http-connection-output-stream
   #:engine-rpc-http-connection-close-function
   #:engine-rpc-http-connection-close
   #:engine-rpc-http-listener
   #:make-engine-rpc-http-listener
   #:make-engine-rpc-http-socket-listener
   #:engine-rpc-http-listener-endpoint
   #:engine-rpc-http-listener-accept-function
   #:engine-rpc-http-listener-close-function
   #:engine-rpc-http-listener-accept
   #:engine-rpc-http-listener-close
   #:engine-rpc-make-jwt-token
   #:rpc-http-handle-request
   #:rpc-http-handle-stream
   #:engine-rpc-handle-http-request-string
   #:engine-rpc-handle-http-stream
   #:engine-rpc-http-service-handle-stream
   #:engine-rpc-http-service-serve-listener))
