(defpackage #:ethereum-lisp.execution-requests
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation)
  (:export
   #:validate-execution-request-fields
   #:validate-execution-request-list-fields
   #:execution-requests-hash))

(defpackage #:ethereum-lisp.block-access-lists
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation)
  (:export
   #:block-access-account
   #:block-access-account-p
   #:make-block-access-account
   #:block-access-account-address
   #:block-access-account-storage-writes
   #:block-access-account-storage-reads
   #:block-access-account-balance-changes
   #:block-access-account-nonce-changes
   #:block-access-account-code-changes
   #:block-access-storage-write
   #:block-access-storage-write-p
   #:make-block-access-storage-write
   #:block-access-storage-write-tx-index
   #:block-access-storage-write-value-after
   #:block-access-slot-writes
   #:block-access-slot-writes-p
   #:make-block-access-slot-writes
   #:block-access-slot-writes-slot
   #:block-access-slot-writes-accesses
   #:block-access-balance-change
   #:block-access-balance-change-p
   #:make-block-access-balance-change
   #:block-access-balance-change-tx-index
   #:block-access-balance-change-balance
   #:block-access-nonce-change
   #:block-access-nonce-change-p
   #:make-block-access-nonce-change
   #:block-access-nonce-change-tx-index
   #:block-access-nonce-change-nonce
   #:block-access-code-change
   #:block-access-code-change-p
   #:make-block-access-code-change
   #:block-access-code-change-tx-index
   #:block-access-code-change-code
   #:block-access-account-rlp
   #:block-access-list-rlp
   #:block-access-list-from-rlp
   #:block-access-list-rlp-hash
   #:block-access-list-hash
   #:block-access-list-item-count
   #:validate-block-access-account-fields
   #:validate-block-access-list-fields))
