(defpackage #:ethereum-lisp.core
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.accounts
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.json
        #:ethereum-lisp.genesis
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool
        #:ethereum-lisp.chain-store.persistence)
  (:import-from #:ethereum-lisp.database
   #:key-value-database
   #:make-kv-write-batch
   #:kv-apply-batch
   #:kv-chain-canonical-hashes
   #:kv-batch-put-chain-record
   #:kv-batch-delete-chain-record
   #:kv-chain-record-entries
   #:kv-batch-put-chain-canonical-hash
   #:kv-batch-delete-chain-canonical-hash
   #:kv-chain-checkpoints
   #:kv-batch-put-chain-checkpoint
   #:kv-batch-delete-chain-checkpoint)
  (:import-from #:ethereum-lisp.validation
   #:block-validation-error
   #:block-validation-error-message
   #:block-validation-fail
   #:ensure-uint256
   #:optional-bytes
   #:rlp-uint-field
   #:rlp-bytes-field
   #:rlp-list-field
   #:rlp-sized-bytes-field
   #:rlp-hash32-field
   #:rlp-address-field
   #:validate-byte-sequence-field
   #:byte-vector-lexicographic<
   #:uint32-value-p
   #:uint64-value-p)
  (:export
   #:+empty-ommers-hash+
   #:ommers-hash
   #:+initial-base-fee+
   #:+base-fee-elasticity-multiplier+
   #:+base-fee-change-denominator+
   #:+blob-gas-per-blob+
   #:+blob-byte-size+
   #:+kzg-proof-size+
   #:*kzg-point-proof-verifier*
   #:*kzg-blob-proof-verifier*
   #:*kzg-verifier-command-timeout-seconds*
   #:kzg-point-proof-verification-available-p
   #:kzg-blob-proof-verification-available-p
   #:kzg-proof-verification-available-p
   #:verify-kzg-point-proof
   #:verify-kzg-blob-proof
   #:make-kzg-point-proof-command-verifier
   #:make-kzg-blob-proof-command-verifier
   #:configure-kzg-proof-command-verifiers
   #:+cell-proofs-per-blob+
   #:+target-blobs-per-block+
   #:+max-blobs-per-block+
   #:+osaka-target-blobs-per-block+
   #:+osaka-max-blobs-per-block+
   #:+bpo1-target-blobs-per-block+
   #:+bpo1-max-blobs-per-block+
   #:+bpo2-target-blobs-per-block+
   #:+bpo2-max-blobs-per-block+
   #:+bpo3-target-blobs-per-block+
   #:+bpo3-max-blobs-per-block+
   #:+bpo4-target-blobs-per-block+
   #:+bpo4-max-blobs-per-block+
   #:+min-blobs-per-transaction+
   #:+min-blob-gas-price+
   #:+blob-base-fee-update-fraction+
   #:+osaka-blob-base-fee-update-fraction+
   #:+bpo1-blob-base-fee-update-fraction+
   #:+bpo2-blob-base-fee-update-fraction+
   #:+bpo3-blob-base-fee-update-fraction+
   #:+bpo4-blob-base-fee-update-fraction+
   #:+blob-base-cost+
   #:+maximum-extra-data-size+
   #:+block-access-list-max-code-size+
   #:+block-access-list-amsterdam-max-code-size+
   #:+block-access-list-item-gas-cost+
   #:+gas-limit-bound-divisor+
   #:+minimum-gas-limit+
   #:+genesis-gas-limit+
   #:+genesis-difficulty+
   #:blob-schedule-entry
   #:make-blob-schedule-entry
   #:blob-schedule-entry-timestamp
   #:blob-schedule-entry-target-blobs
   #:blob-schedule-entry-max-blobs
   #:blob-schedule-entry-update-fraction
   #:genesis-account
   #:make-genesis-account
   #:genesis-account-address
   #:genesis-account-balance
   #:genesis-account-nonce
   #:genesis-account-code
   #:genesis-account-storage
   #:chain-config
   #:make-chain-config
   #:chain-config-chain-id
   #:chain-config-homestead-block
   #:chain-config-dao-fork-block
   #:chain-config-dao-fork-support
   #:chain-config-eip150-block
   #:chain-config-eip155-block
   #:chain-config-eip158-block
   #:chain-config-byzantium-block
   #:chain-config-constantinople-block
   #:chain-config-petersburg-block
   #:chain-config-istanbul-block
   #:chain-config-muir-glacier-block
   #:chain-config-berlin-block
   #:chain-config-london-block
   #:chain-config-arrow-glacier-block
   #:chain-config-gray-glacier-block
   #:chain-config-shanghai-time
   #:chain-config-cancun-time
   #:chain-config-prague-time
   #:chain-config-osaka-time
   #:chain-config-bpo1-time
   #:chain-config-bpo2-time
   #:chain-config-bpo3-time
   #:chain-config-bpo4-time
   #:chain-config-bpo5-time
   #:chain-config-amsterdam-time
   #:chain-config-ubt-time
   #:chain-config-enable-ubt-at-genesis-p
   #:chain-config-terminal-total-difficulty
   #:chain-config-terminal-total-difficulty-passed
   #:chain-config-terminal-block-hash
   #:chain-config-terminal-block-number
   #:chain-config-merge-netsplit-block
   #:chain-config-deposit-contract-address
   #:chain-config-custom-blob-schedule
   #:fork-block-active-p
   #:fork-time-active-p
   #:chain-config-homestead-p
   #:chain-config-dao-fork-p
   #:chain-config-eip150-p
   #:chain-config-eip155-p
   #:chain-config-eip158-p
   #:chain-config-byzantium-p
   #:chain-config-constantinople-p
   #:chain-config-petersburg-p
   #:chain-config-istanbul-p
   #:chain-config-berlin-p
   #:chain-config-london-p
   #:chain-config-shanghai-p
   #:chain-config-cancun-p
   #:chain-config-prague-p
   #:chain-config-osaka-p
   #:chain-config-bpo1-p
   #:chain-config-bpo2-p
   #:chain-config-bpo3-p
   #:chain-config-bpo4-p
   #:chain-config-bpo5-p
   #:chain-config-amsterdam-p
   #:chain-config-ubt-p
   #:chain-config-ubt-genesis-p
   #:chain-config-expanded-blob-schedule-p
   #:chain-config-blob-schedule
   #:parse-json
   #:json-encode
   #:chain-config-from-genesis-config
   #:chain-config-from-genesis-json-string
   #:chain-config-from-genesis-json-file
   #:genesis-alloc-from-genesis-object
   #:genesis-alloc-from-genesis-json-string
   #:genesis-alloc-from-genesis-json-file
   #:genesis-expected-state-root-from-genesis-object
   #:genesis-expected-state-root-from-genesis-json-string
   #:genesis-expected-state-root-from-genesis-json-file
   #:genesis-header-from-genesis-object
   #:genesis-header-from-genesis-json-string
   #:genesis-header-from-genesis-json-file
   #:genesis-block-from-genesis-header
   #:genesis-block-from-genesis-object
   #:genesis-block-from-genesis-json-string
   #:genesis-block-from-genesis-json-file
   #:chain-config-rules
   #:chain-rules
   #:make-chain-rules
   #:chain-rules-chain-id
   #:chain-rules-homestead-p
   #:chain-rules-eip150-p
   #:chain-rules-eip155-p
   #:chain-rules-eip158-p
   #:chain-rules-byzantium-p
   #:chain-rules-constantinople-p
   #:chain-rules-petersburg-p
   #:chain-rules-istanbul-p
   #:chain-rules-berlin-p
   #:chain-rules-london-p
   #:chain-rules-shanghai-p
   #:chain-rules-cancun-p
   #:chain-rules-prague-p
   #:chain-rules-osaka-p
   #:chain-rules-bpo1-p
   #:chain-rules-bpo2-p
   #:chain-rules-bpo3-p
   #:chain-rules-bpo4-p
   #:chain-rules-bpo5-p
   #:chain-rules-amsterdam-p
   #:chain-rules-ubt-p
   #:chain-rules-blob-schedule-target-gas
   #:chain-rules-blob-schedule-max-gas
   #:chain-rules-blob-schedule-update-fraction
   #:chain-rules-expanded-blob-schedule-p
   #:chain-rules-blob-schedule
   #:chain-rules-transaction-type-supported-p
   #:state-account
   #:make-state-account
   #:state-account-nonce
   #:state-account-balance
   #:state-account-storage-root
   #:state-account-code-hash
   #:state-account-rlp
   #:state-account-hash
   #:legacy-transaction
   #:make-legacy-transaction
   #:legacy-transaction-nonce
   #:legacy-transaction-gas-price
   #:legacy-transaction-gas-limit
   #:legacy-transaction-to
   #:legacy-transaction-value
   #:legacy-transaction-data
   #:legacy-transaction-v
   #:legacy-transaction-r
   #:legacy-transaction-s
   #:legacy-transaction-rlp
   #:legacy-transaction-from-rlp
   #:legacy-transaction-hash
   #:legacy-transaction-signing-payload
   #:legacy-transaction-signing-hash
   #:legacy-transaction-protected-p
   #:legacy-transaction-chain-id
   #:legacy-transaction-sender
   #:access-list-entry
   #:make-access-list-entry
   #:access-list-entry-address
   #:access-list-entry-storage-keys
   #:access-list-storage-key-count
   #:access-list-transaction
   #:make-access-list-transaction
   #:access-list-transaction-chain-id
   #:access-list-transaction-nonce
   #:access-list-transaction-gas-price
   #:access-list-transaction-gas-limit
   #:access-list-transaction-to
   #:access-list-transaction-value
   #:access-list-transaction-data
   #:access-list-transaction-access-list
   #:access-list-transaction-y-parity
   #:access-list-transaction-r
   #:access-list-transaction-s
   #:access-list-transaction-encoding
   #:access-list-transaction-from-rlp
   #:access-list-transaction-hash
   #:access-list-transaction-signing-payload
   #:access-list-transaction-signing-hash
   #:access-list-transaction-sender
   #:dynamic-fee-transaction
   #:make-dynamic-fee-transaction
   #:dynamic-fee-transaction-chain-id
   #:dynamic-fee-transaction-nonce
   #:dynamic-fee-transaction-max-priority-fee-per-gas
   #:dynamic-fee-transaction-max-fee-per-gas
   #:dynamic-fee-transaction-gas-limit
   #:dynamic-fee-transaction-to
   #:dynamic-fee-transaction-value
   #:dynamic-fee-transaction-data
   #:dynamic-fee-transaction-access-list
   #:dynamic-fee-transaction-y-parity
   #:dynamic-fee-transaction-r
   #:dynamic-fee-transaction-s
   #:dynamic-fee-transaction-encoding
   #:dynamic-fee-transaction-from-rlp
   #:dynamic-fee-transaction-hash
   #:dynamic-fee-transaction-signing-payload
   #:dynamic-fee-transaction-signing-hash
   #:dynamic-fee-transaction-sender
   #:blob-transaction
   #:make-blob-transaction
   #:blob-transaction-chain-id
   #:blob-transaction-nonce
   #:blob-transaction-gas-limit
   #:blob-transaction-to
   #:blob-transaction-value
   #:blob-transaction-data
   #:blob-transaction-access-list
   #:blob-transaction-y-parity
   #:blob-transaction-r
   #:blob-transaction-s
   #:blob-transaction-max-priority-fee-per-gas
   #:blob-transaction-max-fee-per-gas
   #:blob-transaction-blob-versioned-hashes
   #:blob-transaction-max-fee-per-blob-gas
   #:blob-transaction-encoding
   #:blob-transaction-from-rlp
   #:blob-transaction-hash
   #:blob-transaction-signing-hash
   #:blob-transaction-sender
   #:blob-sidecar
   #:make-blob-sidecar
   #:blob-sidecar-blobs
   #:blob-sidecar-commitments
   #:blob-sidecar-proofs
   #:blob-sidecar-versioned-hashes
   #:set-code-authorization
   #:make-set-code-authorization
   #:set-code-authorization-chain-id
   #:set-code-authorization-address
   #:set-code-authorization-nonce
   #:set-code-authorization-y-parity
   #:set-code-authorization-r
   #:set-code-authorization-s
   #:set-code-authorization-from-rlp-object
   #:set-code-authorization-signing-hash
   #:set-code-authorization-authority
   #:set-code-delegation-code
   #:set-code-delegation-target
   #:set-code-transaction
   #:make-set-code-transaction
   #:set-code-transaction-chain-id
   #:set-code-transaction-nonce
   #:set-code-transaction-max-priority-fee-per-gas
   #:set-code-transaction-max-fee-per-gas
   #:set-code-transaction-gas-limit
   #:set-code-transaction-to
   #:set-code-transaction-value
   #:set-code-transaction-data
   #:set-code-transaction-access-list
   #:set-code-transaction-authorization-list
   #:set-code-transaction-y-parity
   #:set-code-transaction-r
   #:set-code-transaction-s
   #:set-code-transaction-encoding
   #:set-code-transaction-from-rlp
   #:set-code-transaction-hash
   #:set-code-transaction-signing-hash
   #:set-code-transaction-sender
   #:transaction-encoding
   #:transaction-from-encoding
   #:transaction-hash
   #:transaction-sender
   #:transaction-nonce
   #:transaction-gas-limit
   #:transaction-to
   #:transaction-value
   #:transaction-data
   #:transaction-access-list
   #:transaction-authorization-list
   #:transaction-type
   #:validate-transaction-type-for-config
   #:transaction-blob-versioned-hashes
   #:transaction-blob-gas-used
   #:transaction-max-priority-fee-per-gas
   #:transaction-max-fee-per-gas
   #:validate-1559-transaction-fees
   #:transaction-effective-gas-price
   #:transaction-priority-fee-per-gas
   #:block-header
   #:make-block-header
   #:block-header-parent-hash
   #:block-header-ommers-hash
   #:block-header-beneficiary
   #:block-header-state-root
   #:block-header-transactions-root
   #:block-header-receipts-root
   #:block-header-logs-bloom
   #:block-header-difficulty
   #:block-header-number
   #:block-header-gas-limit
   #:block-header-gas-used
   #:block-header-timestamp
   #:block-header-extra-data
   #:block-header-mix-hash
   #:block-header-nonce
   #:block-header-base-fee-per-gas
   #:block-header-withdrawals-root
   #:block-header-blob-gas-used
   #:block-header-excess-blob-gas
   #:block-header-parent-beacon-root
   #:block-header-requests-hash
   #:block-header-block-access-list-hash
   #:block-header-slot-number
   #:block-header-rlp
   #:block-header-hash
   #:ethereum-block
   #:make-block
   #:block-header
   #:block-transactions
   #:block-ommers
   #:block-withdrawals
   #:block-withdrawals-present-p
   #:block-requests
   #:block-requests-present-p
   #:block-block-access-list
   #:block-block-access-list-present-p
   #:block-encoded-block-access-list
   #:block-hash
   #:block-rlp
   #:block-from-rlp
   #:executable-data
   #:make-executable-data
   #:executable-data-parent-hash
   #:executable-data-fee-recipient
   #:executable-data-state-root
   #:executable-data-receipts-root
   #:executable-data-logs-bloom
   #:executable-data-random
   #:executable-data-number
   #:executable-data-gas-limit
   #:executable-data-gas-used
   #:executable-data-timestamp
   #:executable-data-extra-data
   #:executable-data-base-fee-per-gas
   #:executable-data-block-hash
   #:executable-data-transactions
   #:executable-data-withdrawals
   #:executable-data-withdrawals-present-p
   #:executable-data-blob-gas-used
   #:executable-data-excess-blob-gas
   #:executable-data-slot-number
   #:execution-payload-envelope
   #:make-execution-payload-envelope
   #:execution-payload-envelope-execution-payload
   #:execution-payload-envelope-block-value
   #:execution-payload-envelope-blobs-bundle
   #:execution-payload-envelope-requests
   #:execution-payload-envelope-override-p
   #:+payload-status-valid+
   #:+payload-status-invalid+
   #:+payload-status-syncing+
   #:+payload-status-accepted+
   #:payload-status
   #:make-payload-status
   #:payload-status-status
   #:payload-status-latest-valid-hash
   #:payload-status-validation-error
   #:payload-status-witness
   #:forkchoice-state
   #:make-forkchoice-state
   #:forkchoice-state-head-block-hash
   #:forkchoice-state-safe-block-hash
   #:forkchoice-state-finalized-block-hash
   #:payload-attributes-v1
   #:make-payload-attributes-v1
   #:payload-attributes-v1-timestamp
   #:payload-attributes-v1-prev-randao
   #:payload-attributes-v1-suggested-fee-recipient
   #:engine-prepared-payload
   #:make-engine-prepared-payload
   #:engine-prepared-payload-payload-id
   #:engine-prepared-payload-version
   #:engine-prepared-payload-block
   #:block-to-executable-data
   #:executable-data-decoded-transactions
   #:executable-data-to-block-no-hash
   #:executable-data-to-block
   #:engine-new-payload-params-status
   #:engine-new-payload-version-status
   #:chain-store-checkpoint
   #:make-chain-store-checkpoint
   #:chain-store-checkpoint-label
   #:chain-store-checkpoint-block-hash
   #:engine-payload-memory-store
   #:make-engine-payload-memory-store
   #:engine-transaction-location
   #:engine-transaction-location-block
   #:engine-transaction-location-index
   #:engine-transaction-location-transaction
   #:engine-transaction-location-receipt
   #:engine-transaction-location-log-index-start
   #:engine-payload-store-put-block
   #:engine-payload-store-known-block
   #:engine-payload-store-block-by-number
   #:engine-payload-store-canonical-hash
   #:engine-payload-store-transaction-location
   #:engine-payload-store-put-account-balance
   #:engine-payload-store-put-account-nonce
   #:engine-payload-store-put-account-code
   #:engine-payload-store-put-account-storage
   #:engine-payload-store-state-available-p
   #:engine-payload-store-remote-block
   #:engine-payload-store-mark-invalid
   #:engine-payload-store-invalid-block
   #:engine-payload-store-invalid-ancestor-status
   #:engine-payload-id-to-hex
   #:engine-payload-store-put-prepared-payload
   #:engine-payload-store-prepared-payload
   #:chain-store-put-block
   #:chain-store-known-block
   #:chain-store-block-by-number
   #:chain-store-canonical-hash
   #:chain-store-set-canonical-head
   #:chain-store-head-number
   #:chain-store-block-tag-number
   #:chain-store-latest-block
   #:chain-store-transaction-location
   #:chain-store-block-receipts
   #:chain-store-state-available-p
   #:chain-store-prune-state-before
   #:chain-store-atomic-commit
   #:chain-store-put-account-balance
   #:chain-store-account-balance
   #:chain-store-put-account-nonce
   #:chain-store-account-nonce
   #:chain-store-put-account-code
   #:chain-store-account-code
   #:chain-store-put-account-storage
   #:chain-store-account-storage
   #:chain-store-for-each-account
   #:chain-store-update-forkchoice-checkpoints
   #:chain-store-head-checkpoint
   #:chain-store-safe-checkpoint
   #:chain-store-finalized-checkpoint
   #:chain-store-head-block
   #:chain-store-safe-block
   #:chain-store-finalized-block
   #:chain-store-export-indexes-to-kv
   #:chain-store-export-block-records-to-kv
   #:chain-store-export-transaction-locations-to-kv
   #:chain-store-export-state-records-to-kv
   #:chain-store-export-txpool-records-to-kv
   #:chain-store-export-to-kv
   #:engine-payload-store-pooled-transactions
   #:engine-payload-id-with-transactions
   #:engine-payload-store-pending-mining-transactions
   #:engine-select-mining-transactions
   #:chain-store-import-txpool-records-from-kv
   #:chain-store-restore-txpool-consistency
   #:chain-store-import-from-kv
   #:chain-store-put-prepared-payload
   #:chain-store-prepared-payload
   #:engine-payload-store-put-blob-sidecar
   #:engine-payload-store-blob-and-proofs-v1
   #:engine-payload-store-blob-and-proofs-v2
   #:+engine-rpc-capabilities+
   #:engine-rpc-capabilities
   #:+engine-rpc-client-version+
   #:engine-rpc-client-version
   #:engine-rpc-transition-configuration-object
   #:engine-rpc-executable-data-from-object
   #:engine-rpc-executable-data-object
   #:engine-rpc-payload-status-object
   #:engine-rpc-forkchoice-state-from-object
   #:engine-forkchoice-memory-status
   #:engine-rpc-forkchoice-response-object
   #:engine-rpc-handle-get-payload-v1
   #:engine-rpc-handle-forkchoice-updated-v1
   #:engine-rpc-engine-method-p
   #:engine-rpc-public-method-p
   #:engine-rpc-any-method-p
   #:engine-rpc-handle-request
   #:engine-rpc-handle-request-value
   #:engine-rpc-handle-request-string
   #:engine-rpc-handle-request-json
   #:+engine-rpc-http-accepted-content-types+
   #:engine-rpc-http-accepted-content-type-p
   #:+engine-rpc-default-http-host+
   #:+engine-rpc-default-http-port+
   #:+engine-rpc-jwt-expiry-seconds+
   #:engine-rpc-http-service
   #:make-engine-rpc-http-service
   #:engine-rpc-http-service-host
   #:engine-rpc-http-service-port
   #:engine-rpc-http-service-store
   #:engine-rpc-http-service-config
   #:engine-rpc-http-service-jwt-secret
   #:engine-rpc-http-service-now-provider
   #:engine-rpc-http-service-import-function
   #:engine-rpc-http-service-telemetry-sink
   #:engine-rpc-http-service-allowed-method-p
   #:engine-rpc-http-service-coinbase
   #:engine-rpc-http-service-rpc-prefix
   #:engine-rpc-http-service-endpoint
   #:engine-rpc-http-connection
   #:make-engine-rpc-http-connection
   #:engine-rpc-http-connection-input-stream
   #:engine-rpc-http-connection-output-stream
   #:engine-rpc-http-connection-close-function
   #:engine-rpc-http-connection-close
   #:engine-rpc-http-listener
   #:make-engine-rpc-http-listener
   #:make-engine-rpc-http-socket-listener
   #:engine-rpc-http-listener-endpoint
   #:engine-rpc-http-listener-accept-function
   #:engine-rpc-http-listener-close-function
   #:engine-rpc-http-listener-accept
   #:engine-rpc-http-listener-close
   #:engine-rpc-make-jwt-token
   #:engine-rpc-handle-http-request-string
   #:engine-rpc-handle-http-stream
   #:engine-rpc-http-service-handle-stream
   #:engine-rpc-http-service-serve-listener
   #:engine-new-payload-memory-status
   #:execution-requests-hash
   #:block-access-account
   #:make-block-access-account
   #:block-access-account-address
   #:block-access-account-storage-writes
   #:block-access-account-storage-reads
   #:block-access-account-balance-changes
   #:block-access-account-nonce-changes
   #:block-access-account-code-changes
   #:block-access-storage-write
   #:make-block-access-storage-write
   #:block-access-storage-write-tx-index
   #:block-access-storage-write-value-after
   #:block-access-slot-writes
   #:make-block-access-slot-writes
   #:block-access-slot-writes-slot
   #:block-access-slot-writes-accesses
   #:block-access-balance-change
   #:make-block-access-balance-change
   #:block-access-balance-change-tx-index
   #:block-access-balance-change-balance
   #:block-access-nonce-change
   #:make-block-access-nonce-change
   #:block-access-nonce-change-tx-index
   #:block-access-nonce-change-nonce
   #:block-access-code-change
   #:make-block-access-code-change
   #:block-access-code-change-tx-index
   #:block-access-code-change-code
   #:block-access-account-rlp
   #:block-access-list-rlp
   #:block-access-list-from-rlp
   #:block-access-list-rlp-hash
   #:block-access-list-hash
   #:block-access-list-item-count
   #:block-validation-error
   #:block-validation-error-message
   #:expected-base-fee-per-gas
   #:validate-block-base-fee
   #:validate-gas-limit-delta
   #:adjusted-parent-gas-limit-for-1559
   #:validate-block-blob-gas-fields
   #:expected-excess-blob-gas
   #:fake-exponential
   #:blob-base-fee
   #:block-header-blob-base-fee
   #:validate-block-excess-blob-gas
   #:block-header-cancun-fields-present-p
   #:validate-block-cancun-fields
   #:validate-block-withdrawals-field
   #:validate-block-requests-hash-field
   #:block-header-amsterdam-fields-present-p
   #:validate-block-amsterdam-fields
   #:validate-block-amsterdam-slot-number
   #:validate-block-header-basics
   #:validate-block-header-against-config
   #:validate-blob-versioned-hash
   #:validate-blob-transaction-fields
   #:validate-blob-transaction-fee-cap
   #:validate-blob-sidecar-fields
   #:validate-withdrawal-fields
   #:validate-withdrawal-list-fields
   #:validate-execution-request-fields
   #:validate-execution-request-list-fields
   #:validate-block-access-account-fields
   #:validate-block-access-list-fields
   #:validate-block-transactions-against-config
   #:validate-block-body-against-config
   #:validate-block-against-config
   #:validate-block-body-roots
   #:blob-gas-used
   #:receipts-gas-used
   #:validate-block-execution-roots
   #:withdrawal
   #:make-withdrawal
   #:withdrawal-index
   #:withdrawal-validator-index
   #:withdrawal-address
   #:withdrawal-amount
   #:withdrawal-rlp
   #:withdrawal-list-root
   #:log-entry
   #:make-log-entry
   #:log-entry-address
   #:log-entry-topics
   #:log-entry-data
   #:log-entry-rlp-object
   #:bloom
   #:make-bloom
   #:bloom-bytes
   #:bloom-add
   #:bloom-contains-p
   #:receipt
   #:make-receipt
   #:receipt-status
   #:receipt-cumulative-gas-used
   #:receipt-logs
   #:receipt-rlp
   #:transaction-receipt-encoding
   #:receipt-bloom
   #:derive-list-root
   #:transaction-list-root
   #:receipt-list-root
   #:transaction-receipt-list-root))
