(defpackage #:ethereum-lisp.consensus
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks)
  (:export
   #:+base-fee-elasticity-multiplier+
   #:+base-fee-change-denominator+
   #:+min-blob-gas-price+
   #:+min-blobs-per-transaction+
   #:+blob-base-cost+
   #:+gas-limit-bound-divisor+
   #:+minimum-gas-limit+
   #:expected-base-fee-per-gas
   #:hash32=
   #:validate-sized-byte-vector
   #:validate-optional-hash32-field
   #:validate-optional-address-field
   #:validate-optional-uint256-field
   #:validate-optional-uint64-field
   #:validate-blob-versioned-hash
   #:validate-blob-transaction-fields
   #:validate-blob-transaction-fee-cap
   #:validate-transaction-data-field
   #:validate-transaction-recipient-field
   #:validate-transaction-scalar-fields
   #:validate-transaction-signature-fields
   #:validate-access-list-fields
   #:validate-set-code-authorization-fields
   #:validate-set-code-transaction-fields
   #:validate-set-code-authorization-signatures
   #:validate-block-base-fee
   #:validate-gas-limit-delta
   #:adjusted-parent-gas-limit-for-1559
   #:validate-block-blob-gas-fields
   #:expected-excess-blob-gas
   #:fake-exponential
   #:blob-base-fee
   #:block-header-blob-base-fee
   #:validate-block-excess-blob-gas
   #:block-header-cancun-fields-present-p
   #:validate-block-cancun-fields
   #:validate-block-withdrawals-field
   #:validate-block-requests-hash-field
   #:block-header-amsterdam-fields-present-p
   #:validate-block-amsterdam-fields
   #:validate-block-amsterdam-slot-number
   #:validate-block-header-basics
   #:validate-block-header-against-config
   #:validate-withdrawal-fields
   #:validate-withdrawal-list-fields
   #:validate-block-transactions-against-config
   #:validate-block-body-against-config
   #:validate-block-against-config
   #:validate-block-body-roots
   #:transaction-blob-count
   #:blob-gas-used
   #:receipts-gas-used
   #:validate-block-execution-roots))
