(defpackage #:ethereum-lisp.node-store.persistence
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.database
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.accounts
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.txpool.index
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store.state
        #:ethereum-lisp.node-state
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.txpool)
  (:import-from #:ethereum-lisp.canonical-chain
                #:canonical-chain-transition-p
                #:canonical-chain-transition-installed-blocks
                #:canonical-chain-transition-displaced-blocks
                #:canonical-chain-transition-changed-txpool-hashes)
  (:export
   #:node-store-persistence-metadata
   #:make-node-store-persistence-metadata
   #:node-store-persistence-metadata-role
   #:node-store-persistence-metadata-generation
   #:node-store-persistence-metadata-chain-id
   #:node-store-persistence-metadata-genesis-hash
   #:node-store-persistence-metadata-authority-id
   #:node-store-persistence-metadata-base-chain-generation
   #:node-store-read-persistence-metadata
   #:node-store-stage-progress
   #:node-store-stage-progress-p
   #:node-store-stage-progress-number
   #:node-store-stage-progress-block-hash
   #:node-store-staged-import-state
   #:node-store-staged-import-state-p
   #:node-store-staged-import-state-revision
   #:node-store-staged-import-state-mode
   #:node-store-staged-import-state-authority-id
   #:node-store-staged-import-state-chain-id
   #:node-store-staged-import-state-genesis-hash
   #:node-store-staged-import-state-chain-config-fingerprint
   #:node-store-staged-import-state-anchor
   #:node-store-staged-import-state-target
   #:node-store-staged-import-state-unwind-target
   #:node-store-staged-import-stages
   #:node-store-staged-import-stage-progress
   #:node-store-read-staged-import-state
   #:node-store-begin-staged-import
   #:node-store-validate-staged-import
   #:node-store-staged-import-next-action
   #:node-store-forward-staged-import-block
   #:node-store-begin-staged-unwind
   #:node-store-unwind-staged-import-step
   #:node-store-hydrate-staged-import
   #:chain-store-export-indexes-to-kv
   #:chain-store-export-block-records-to-kv
   #:chain-store-export-transaction-locations-to-kv
   #:chain-store-export-state-records-to-kv
   #:node-store-export-txpool-records-to-kv
   #:node-store-export-payload-candidate-to-kv
   #:node-store-export-forkchoice-to-kv
   #:node-store-export-to-kv
   #:node-store-import-txpool-records-from-kv
   #:node-store-restore-txpool-consistency
   #:node-store-import-from-kv))
