(defpackage #:ethereum-lisp.bytes
  (:use #:cl)
  (:export
   #:byte-vector
   #:byte-vector-p
   #:make-byte-vector
   #:ensure-byte-vector
   #:bytes=
   #:concat-bytes
   #:integer-to-minimal-bytes
   #:bytes-to-integer
   #:ascii-to-bytes
   #:bytes-to-ascii))

(defpackage #:ethereum-lisp.hex
  (:use #:cl #:ethereum-lisp.bytes)
  (:export
   #:bytes-to-hex
   #:hex-to-bytes
   #:quantity-to-hex
   #:hex-to-quantity))

(defpackage #:ethereum-lisp.rlp
  (:use #:cl #:ethereum-lisp.bytes)
  (:export
   #:rlp-error
   #:rlp-list
   #:rlp-list-p
   #:rlp-list-items
   #:make-rlp-list
   #:rlp-encode
   #:rlp-decode
   #:rlp-decode-one))

(defpackage #:ethereum-lisp.types
  (:use #:cl #:ethereum-lisp.bytes #:ethereum-lisp.hex)
  (:export
   #:+uint256-max+
   #:uint256-p
   #:address
   #:address-p
   #:address-bytes
   #:make-address
   #:address-from-hex
   #:address-to-hex
   #:zero-address
   #:hash32
   #:hash32-p
   #:hash32-bytes
   #:make-hash32
   #:hash32-from-hex
   #:hash32-to-hex
   #:zero-hash32))

(defpackage #:ethereum-lisp.crypto
  (:use #:cl #:ethereum-lisp.bytes #:ethereum-lisp.hex #:ethereum-lisp.types)
  (:export
   #:keccak-256
   #:keccak-256-hash
   #:keccak-256-hex
   #:sha256
   #:sha256-hash
   #:sha256-hex
   #:ripemd160
   #:ripemd160-hex
   #:secp256k1-recover-public-key
   #:secp256k1-recover-address
   #:secp256k1-valid-signature-values-p
   #:+kzg-commitment-size+
   #:+kzg-commitment-version+
   #:kzg-commitment-to-versioned-hash
   #:+empty-code-hash+
   #:+empty-trie-hash+))

(defpackage #:ethereum-lisp.trie.encoding
  (:use #:cl #:ethereum-lisp.bytes)
  (:export
   #:+terminator-nibble+
   #:has-terminator-p
   #:keybytes-to-nibbles
   #:nibbles-to-keybytes
   #:hex-prefix-encode
   #:hex-prefix-decode
   #:common-prefix-length))

(defpackage #:ethereum-lisp.trie
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie.encoding)
  (:export
   #:mpt
   #:make-mpt
   #:mpt-put
   #:mpt-get
   #:mpt-root-hash
   #:mpt-root-hex
   #:mpt-root-node))

(defpackage #:ethereum-lisp.core
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie)
  (:export
   #:+empty-ommers-hash+
   #:+initial-base-fee+
   #:+base-fee-elasticity-multiplier+
   #:+base-fee-change-denominator+
   #:+blob-gas-per-blob+
   #:+blob-byte-size+
   #:+kzg-proof-size+
   #:+target-blobs-per-block+
   #:+max-blobs-per-block+
   #:+osaka-target-blobs-per-block+
   #:+osaka-max-blobs-per-block+
   #:+bpo1-target-blobs-per-block+
   #:+bpo1-max-blobs-per-block+
   #:+bpo2-target-blobs-per-block+
   #:+bpo2-max-blobs-per-block+
   #:+bpo3-target-blobs-per-block+
   #:+bpo3-max-blobs-per-block+
   #:+bpo4-target-blobs-per-block+
   #:+bpo4-max-blobs-per-block+
   #:+min-blobs-per-transaction+
   #:+min-blob-gas-price+
   #:+blob-base-fee-update-fraction+
   #:+osaka-blob-base-fee-update-fraction+
   #:+bpo1-blob-base-fee-update-fraction+
   #:+bpo2-blob-base-fee-update-fraction+
   #:+bpo3-blob-base-fee-update-fraction+
   #:+bpo4-blob-base-fee-update-fraction+
   #:+blob-base-cost+
   #:+maximum-extra-data-size+
   #:+block-access-list-max-code-size+
   #:+block-access-list-amsterdam-max-code-size+
   #:+block-access-list-item-gas-cost+
   #:+gas-limit-bound-divisor+
   #:+minimum-gas-limit+
   #:+genesis-gas-limit+
   #:+genesis-difficulty+
   #:blob-schedule-entry
   #:make-blob-schedule-entry
   #:blob-schedule-entry-timestamp
   #:blob-schedule-entry-target-blobs
   #:blob-schedule-entry-max-blobs
   #:blob-schedule-entry-update-fraction
   #:genesis-account
   #:make-genesis-account
   #:genesis-account-address
   #:genesis-account-balance
   #:genesis-account-nonce
   #:genesis-account-code
   #:genesis-account-storage
   #:chain-config
   #:make-chain-config
   #:chain-config-chain-id
   #:chain-config-homestead-block
   #:chain-config-dao-fork-block
   #:chain-config-dao-fork-support
   #:chain-config-eip150-block
   #:chain-config-eip155-block
   #:chain-config-eip158-block
   #:chain-config-byzantium-block
   #:chain-config-constantinople-block
   #:chain-config-petersburg-block
   #:chain-config-istanbul-block
   #:chain-config-muir-glacier-block
   #:chain-config-berlin-block
   #:chain-config-london-block
   #:chain-config-arrow-glacier-block
   #:chain-config-gray-glacier-block
   #:chain-config-shanghai-time
   #:chain-config-cancun-time
   #:chain-config-prague-time
   #:chain-config-osaka-time
   #:chain-config-bpo1-time
   #:chain-config-bpo2-time
   #:chain-config-bpo3-time
   #:chain-config-bpo4-time
   #:chain-config-bpo5-time
   #:chain-config-amsterdam-time
   #:chain-config-ubt-time
   #:chain-config-enable-ubt-at-genesis-p
   #:chain-config-terminal-total-difficulty
   #:chain-config-terminal-total-difficulty-passed
   #:chain-config-merge-netsplit-block
   #:chain-config-deposit-contract-address
   #:chain-config-custom-blob-schedule
   #:fork-block-active-p
   #:fork-time-active-p
   #:chain-config-homestead-p
   #:chain-config-dao-fork-p
   #:chain-config-eip150-p
   #:chain-config-eip155-p
   #:chain-config-eip158-p
   #:chain-config-byzantium-p
   #:chain-config-constantinople-p
   #:chain-config-petersburg-p
   #:chain-config-istanbul-p
   #:chain-config-berlin-p
   #:chain-config-london-p
   #:chain-config-shanghai-p
   #:chain-config-cancun-p
   #:chain-config-prague-p
   #:chain-config-osaka-p
   #:chain-config-bpo1-p
   #:chain-config-bpo2-p
   #:chain-config-bpo3-p
   #:chain-config-bpo4-p
   #:chain-config-bpo5-p
   #:chain-config-amsterdam-p
   #:chain-config-ubt-p
   #:chain-config-ubt-genesis-p
   #:chain-config-expanded-blob-schedule-p
   #:chain-config-blob-schedule
   #:parse-json
   #:chain-config-from-genesis-config
   #:chain-config-from-genesis-json-string
   #:chain-config-from-genesis-json-file
   #:genesis-alloc-from-genesis-object
   #:genesis-alloc-from-genesis-json-string
   #:genesis-alloc-from-genesis-json-file
   #:genesis-expected-state-root-from-genesis-object
   #:genesis-expected-state-root-from-genesis-json-string
   #:genesis-expected-state-root-from-genesis-json-file
   #:genesis-header-from-genesis-object
   #:genesis-header-from-genesis-json-string
   #:genesis-header-from-genesis-json-file
   #:genesis-block-from-genesis-header
   #:genesis-block-from-genesis-object
   #:genesis-block-from-genesis-json-string
   #:genesis-block-from-genesis-json-file
   #:chain-config-rules
   #:chain-rules
   #:make-chain-rules
   #:chain-rules-chain-id
   #:chain-rules-homestead-p
   #:chain-rules-eip150-p
   #:chain-rules-eip155-p
   #:chain-rules-eip158-p
   #:chain-rules-byzantium-p
   #:chain-rules-constantinople-p
   #:chain-rules-petersburg-p
   #:chain-rules-istanbul-p
   #:chain-rules-berlin-p
   #:chain-rules-london-p
   #:chain-rules-shanghai-p
   #:chain-rules-cancun-p
   #:chain-rules-prague-p
   #:chain-rules-osaka-p
   #:chain-rules-bpo1-p
   #:chain-rules-bpo2-p
   #:chain-rules-bpo3-p
   #:chain-rules-bpo4-p
   #:chain-rules-bpo5-p
   #:chain-rules-amsterdam-p
   #:chain-rules-ubt-p
   #:chain-rules-blob-schedule-target-gas
   #:chain-rules-blob-schedule-max-gas
   #:chain-rules-blob-schedule-update-fraction
   #:chain-rules-expanded-blob-schedule-p
   #:chain-rules-blob-schedule
   #:chain-rules-transaction-type-supported-p
   #:state-account
   #:make-state-account
   #:state-account-nonce
   #:state-account-balance
   #:state-account-storage-root
   #:state-account-code-hash
   #:state-account-rlp
   #:state-account-hash
   #:legacy-transaction
   #:make-legacy-transaction
   #:legacy-transaction-nonce
   #:legacy-transaction-gas-price
   #:legacy-transaction-gas-limit
   #:legacy-transaction-to
   #:legacy-transaction-value
   #:legacy-transaction-data
   #:legacy-transaction-v
   #:legacy-transaction-r
   #:legacy-transaction-s
   #:legacy-transaction-rlp
   #:legacy-transaction-hash
   #:legacy-transaction-signing-payload
   #:legacy-transaction-signing-hash
   #:legacy-transaction-protected-p
   #:legacy-transaction-chain-id
   #:legacy-transaction-sender
   #:access-list-entry
   #:make-access-list-entry
   #:access-list-entry-address
   #:access-list-entry-storage-keys
   #:access-list-storage-key-count
   #:access-list-transaction
   #:make-access-list-transaction
   #:access-list-transaction-chain-id
   #:access-list-transaction-y-parity
   #:access-list-transaction-r
   #:access-list-transaction-s
   #:access-list-transaction-encoding
   #:access-list-transaction-hash
   #:access-list-transaction-signing-payload
   #:access-list-transaction-signing-hash
   #:access-list-transaction-sender
   #:dynamic-fee-transaction
   #:make-dynamic-fee-transaction
   #:dynamic-fee-transaction-max-priority-fee-per-gas
   #:dynamic-fee-transaction-max-fee-per-gas
   #:dynamic-fee-transaction-chain-id
   #:dynamic-fee-transaction-y-parity
   #:dynamic-fee-transaction-r
   #:dynamic-fee-transaction-s
   #:dynamic-fee-transaction-encoding
   #:dynamic-fee-transaction-hash
   #:dynamic-fee-transaction-signing-payload
   #:dynamic-fee-transaction-signing-hash
   #:dynamic-fee-transaction-sender
   #:blob-transaction
   #:make-blob-transaction
   #:blob-transaction-chain-id
   #:blob-transaction-y-parity
   #:blob-transaction-r
   #:blob-transaction-s
   #:blob-transaction-max-priority-fee-per-gas
   #:blob-transaction-max-fee-per-gas
   #:blob-transaction-blob-versioned-hashes
   #:blob-transaction-max-fee-per-blob-gas
   #:blob-transaction-encoding
   #:blob-transaction-hash
   #:blob-transaction-signing-hash
   #:blob-transaction-sender
   #:blob-sidecar
   #:make-blob-sidecar
   #:blob-sidecar-blobs
   #:blob-sidecar-commitments
   #:blob-sidecar-proofs
   #:blob-sidecar-versioned-hashes
   #:set-code-authorization
   #:make-set-code-authorization
   #:set-code-authorization-chain-id
   #:set-code-authorization-address
   #:set-code-authorization-nonce
   #:set-code-authorization-y-parity
   #:set-code-authorization-r
   #:set-code-authorization-s
   #:set-code-authorization-signing-hash
   #:set-code-authorization-authority
   #:set-code-delegation-code
   #:set-code-delegation-target
   #:set-code-transaction
   #:make-set-code-transaction
   #:set-code-transaction-chain-id
   #:set-code-transaction-y-parity
   #:set-code-transaction-r
   #:set-code-transaction-s
   #:set-code-transaction-encoding
   #:set-code-transaction-hash
   #:set-code-transaction-signing-hash
   #:set-code-transaction-sender
   #:transaction-encoding
   #:transaction-hash
   #:transaction-sender
   #:transaction-nonce
   #:transaction-gas-limit
   #:transaction-to
   #:transaction-value
   #:transaction-data
   #:transaction-access-list
   #:transaction-authorization-list
   #:transaction-type
   #:validate-transaction-type-for-config
   #:transaction-blob-versioned-hashes
   #:transaction-blob-gas-used
   #:transaction-max-priority-fee-per-gas
   #:transaction-max-fee-per-gas
   #:validate-1559-transaction-fees
   #:transaction-effective-gas-price
   #:transaction-priority-fee-per-gas
   #:block-header
   #:make-block-header
   #:block-header-parent-hash
   #:block-header-ommers-hash
   #:block-header-beneficiary
   #:block-header-state-root
   #:block-header-transactions-root
   #:block-header-receipts-root
   #:block-header-logs-bloom
   #:block-header-difficulty
   #:block-header-number
   #:block-header-gas-limit
   #:block-header-gas-used
   #:block-header-timestamp
   #:block-header-extra-data
   #:block-header-mix-hash
   #:block-header-nonce
   #:block-header-base-fee-per-gas
   #:block-header-withdrawals-root
   #:block-header-blob-gas-used
   #:block-header-excess-blob-gas
   #:block-header-parent-beacon-root
   #:block-header-requests-hash
   #:block-header-block-access-list-hash
   #:block-header-slot-number
   #:block-header-rlp
   #:block-header-hash
   #:ethereum-block
   #:make-block
   #:block-header
   #:block-transactions
   #:block-ommers
   #:block-withdrawals
   #:block-withdrawals-present-p
   #:block-requests
   #:block-requests-present-p
   #:block-block-access-list
   #:block-block-access-list-present-p
   #:block-encoded-block-access-list
   #:block-hash
   #:execution-requests-hash
   #:block-access-account
   #:make-block-access-account
   #:block-access-account-address
   #:block-access-account-storage-writes
   #:block-access-account-storage-reads
   #:block-access-account-balance-changes
   #:block-access-account-nonce-changes
   #:block-access-account-code-changes
   #:block-access-storage-write
   #:make-block-access-storage-write
   #:block-access-storage-write-tx-index
   #:block-access-storage-write-value-after
   #:block-access-slot-writes
   #:make-block-access-slot-writes
   #:block-access-slot-writes-slot
   #:block-access-slot-writes-accesses
   #:block-access-balance-change
   #:make-block-access-balance-change
   #:block-access-balance-change-tx-index
   #:block-access-balance-change-balance
   #:block-access-nonce-change
   #:make-block-access-nonce-change
   #:block-access-nonce-change-tx-index
   #:block-access-nonce-change-nonce
   #:block-access-code-change
   #:make-block-access-code-change
   #:block-access-code-change-tx-index
   #:block-access-code-change-code
   #:block-access-account-rlp
   #:block-access-list-rlp
   #:block-access-list-from-rlp
   #:block-access-list-rlp-hash
   #:block-access-list-hash
   #:block-access-list-item-count
   #:block-validation-error
   #:block-validation-error-message
   #:expected-base-fee-per-gas
   #:validate-block-base-fee
   #:validate-gas-limit-delta
   #:adjusted-parent-gas-limit-for-1559
   #:validate-block-blob-gas-fields
   #:expected-excess-blob-gas
   #:fake-exponential
   #:blob-base-fee
   #:block-header-blob-base-fee
   #:validate-block-excess-blob-gas
   #:block-header-cancun-fields-present-p
   #:validate-block-cancun-fields
   #:validate-block-withdrawals-field
   #:validate-block-requests-hash-field
   #:block-header-amsterdam-fields-present-p
   #:validate-block-amsterdam-fields
   #:validate-block-amsterdam-slot-number
   #:validate-block-header-basics
   #:validate-block-header-against-config
   #:validate-blob-versioned-hash
   #:validate-blob-transaction-fields
   #:validate-blob-transaction-fee-cap
   #:validate-blob-sidecar-fields
   #:validate-withdrawal-fields
   #:validate-withdrawal-list-fields
   #:validate-execution-request-fields
   #:validate-execution-request-list-fields
   #:validate-block-access-account-fields
   #:validate-block-access-list-fields
   #:validate-block-transactions-against-config
   #:validate-block-body-against-config
   #:validate-block-against-config
   #:validate-block-body-roots
   #:blob-gas-used
   #:receipts-gas-used
   #:validate-block-execution-roots
   #:withdrawal
   #:make-withdrawal
   #:withdrawal-index
   #:withdrawal-validator-index
   #:withdrawal-address
   #:withdrawal-amount
   #:withdrawal-rlp
   #:withdrawal-list-root
   #:log-entry
   #:make-log-entry
   #:log-entry-address
   #:log-entry-topics
   #:log-entry-data
   #:log-entry-rlp-object
   #:bloom
   #:make-bloom
   #:bloom-bytes
   #:bloom-add
   #:bloom-contains-p
   #:receipt
   #:make-receipt
   #:receipt-status
   #:receipt-cumulative-gas-used
   #:receipt-logs
   #:receipt-rlp
   #:transaction-receipt-encoding
   #:receipt-bloom
   #:derive-list-root
   #:transaction-list-root
   #:receipt-list-root
   #:transaction-receipt-list-root))

(defpackage #:ethereum-lisp.state
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie
        #:ethereum-lisp.core)
  (:export
   #:state-db
   #:make-state-db
   #:state-db-get-account
   #:state-db-set-account
   #:state-db-set-code
   #:state-db-get-code
   #:state-db-get-code-hash
   #:state-db-copy
   #:state-db-restore
   #:state-db-set-storage
   #:state-db-get-storage
   #:state-db-root
   #:state-db-root-hex
   #:apply-genesis-account
   #:apply-genesis-alloc
   #:state-db-from-genesis-alloc
   #:state-db-from-genesis-json-string
   #:state-db-from-genesis-json-file
   #:genesis-state-root-from-genesis-alloc
   #:genesis-state-root-from-genesis-json-string
   #:genesis-state-root-from-genesis-json-file
   #:validate-genesis-state-root
   #:validate-genesis-json-state-root
   #:genesis-header-from-state-genesis-object
   #:genesis-header-from-state-genesis-json-string
   #:genesis-header-from-state-genesis-json-file
   #:genesis-block-from-state-genesis-object
   #:genesis-block-from-state-genesis-json-string
   #:genesis-block-from-state-genesis-json-file
   #:+wei-per-gwei+
   #:state-db-add-balance
   #:apply-withdrawal
   #:apply-withdrawals
   #:transaction-validation-error
   #:transaction-intrinsic-gas
   #:apply-legacy-transaction
   #:apply-message
   #:apply-message-list
   #:execution-result
   #:make-execution-result
   #:execution-result-receipts
   #:execution-result-state-root
   #:execution-result-transactions-root
   #:execution-result-receipts-root
   #:execute-legacy-transactions))

(defpackage #:ethereum-lisp.evm
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.rlp
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.core
        #:ethereum-lisp.state)
  (:export
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:execute-bytecode))

(defpackage #:ethereum-lisp.execution
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.rlp
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.core
        #:ethereum-lisp.state
        #:ethereum-lisp.evm)
  (:export
   #:apply-legacy-message
   #:apply-signed-message
   #:apply-signed-message-list
   #:execute-legacy-messages
   #:execute-signed-messages
   #:execute-legacy-block
   #:execute-signed-block))

(defpackage #:ethereum-lisp
  (:use #:cl)
  (:import-from #:ethereum-lisp.bytes
   #:byte-vector
   #:byte-vector-p
   #:make-byte-vector
   #:ensure-byte-vector
   #:bytes=
   #:concat-bytes
   #:integer-to-minimal-bytes
   #:bytes-to-integer
   #:ascii-to-bytes
   #:bytes-to-ascii)
  (:import-from #:ethereum-lisp.hex
   #:bytes-to-hex
   #:hex-to-bytes
   #:quantity-to-hex
   #:hex-to-quantity)
  (:import-from #:ethereum-lisp.rlp
   #:rlp-error
   #:rlp-list
   #:rlp-list-p
   #:rlp-list-items
   #:make-rlp-list
   #:rlp-encode
   #:rlp-decode
   #:rlp-decode-one)
  (:import-from #:ethereum-lisp.types
   #:+uint256-max+
   #:uint256-p
   #:address
   #:address-p
   #:address-bytes
   #:make-address
   #:address-from-hex
   #:address-to-hex
   #:zero-address
   #:hash32
   #:hash32-p
   #:hash32-bytes
   #:make-hash32
   #:hash32-from-hex
   #:hash32-to-hex
   #:zero-hash32)
  (:import-from #:ethereum-lisp.crypto
   #:keccak-256
   #:keccak-256-hash
   #:keccak-256-hex
   #:sha256
   #:sha256-hash
   #:sha256-hex
   #:ripemd160
   #:ripemd160-hex
   #:secp256k1-recover-public-key
   #:secp256k1-recover-address
   #:secp256k1-valid-signature-values-p
   #:+kzg-commitment-size+
   #:+kzg-commitment-version+
   #:kzg-commitment-to-versioned-hash
   #:+empty-code-hash+
   #:+empty-trie-hash+)
  (:import-from #:ethereum-lisp.trie.encoding
   #:+terminator-nibble+
   #:has-terminator-p
   #:keybytes-to-nibbles
   #:nibbles-to-keybytes
   #:hex-prefix-encode
   #:hex-prefix-decode
   #:common-prefix-length)
  (:import-from #:ethereum-lisp.trie
   #:mpt
   #:make-mpt
   #:mpt-put
   #:mpt-get
   #:mpt-root-hash
   #:mpt-root-hex
   #:mpt-root-node)
  (:import-from #:ethereum-lisp.core
   #:+empty-ommers-hash+
   #:+initial-base-fee+
   #:+base-fee-elasticity-multiplier+
   #:+base-fee-change-denominator+
   #:+blob-gas-per-blob+
   #:+blob-byte-size+
   #:+kzg-proof-size+
   #:+target-blobs-per-block+
   #:+max-blobs-per-block+
   #:+osaka-target-blobs-per-block+
   #:+osaka-max-blobs-per-block+
   #:+bpo1-target-blobs-per-block+
   #:+bpo1-max-blobs-per-block+
   #:+bpo2-target-blobs-per-block+
   #:+bpo2-max-blobs-per-block+
   #:+bpo3-target-blobs-per-block+
   #:+bpo3-max-blobs-per-block+
   #:+bpo4-target-blobs-per-block+
   #:+bpo4-max-blobs-per-block+
   #:+min-blobs-per-transaction+
   #:+min-blob-gas-price+
   #:+blob-base-fee-update-fraction+
   #:+osaka-blob-base-fee-update-fraction+
   #:+bpo1-blob-base-fee-update-fraction+
   #:+bpo2-blob-base-fee-update-fraction+
   #:+bpo3-blob-base-fee-update-fraction+
   #:+bpo4-blob-base-fee-update-fraction+
   #:+blob-base-cost+
   #:+maximum-extra-data-size+
   #:+block-access-list-max-code-size+
   #:+block-access-list-amsterdam-max-code-size+
   #:+block-access-list-item-gas-cost+
   #:+gas-limit-bound-divisor+
   #:+minimum-gas-limit+
   #:+genesis-gas-limit+
   #:+genesis-difficulty+
   #:blob-schedule-entry
   #:make-blob-schedule-entry
   #:blob-schedule-entry-timestamp
   #:blob-schedule-entry-target-blobs
   #:blob-schedule-entry-max-blobs
   #:blob-schedule-entry-update-fraction
   #:genesis-account
   #:make-genesis-account
   #:genesis-account-address
   #:genesis-account-balance
   #:genesis-account-nonce
   #:genesis-account-code
   #:genesis-account-storage
   #:chain-config
   #:make-chain-config
   #:chain-config-chain-id
   #:chain-config-homestead-block
   #:chain-config-dao-fork-block
   #:chain-config-dao-fork-support
   #:chain-config-eip150-block
   #:chain-config-eip155-block
   #:chain-config-eip158-block
   #:chain-config-byzantium-block
   #:chain-config-constantinople-block
   #:chain-config-petersburg-block
   #:chain-config-istanbul-block
   #:chain-config-muir-glacier-block
   #:chain-config-berlin-block
   #:chain-config-london-block
   #:chain-config-arrow-glacier-block
   #:chain-config-gray-glacier-block
   #:chain-config-shanghai-time
   #:chain-config-cancun-time
   #:chain-config-prague-time
   #:chain-config-osaka-time
   #:chain-config-bpo1-time
   #:chain-config-bpo2-time
   #:chain-config-bpo3-time
   #:chain-config-bpo4-time
   #:chain-config-bpo5-time
   #:chain-config-amsterdam-time
   #:chain-config-ubt-time
   #:chain-config-enable-ubt-at-genesis-p
   #:chain-config-terminal-total-difficulty
   #:chain-config-terminal-total-difficulty-passed
   #:chain-config-merge-netsplit-block
   #:chain-config-deposit-contract-address
   #:chain-config-custom-blob-schedule
   #:fork-block-active-p
   #:fork-time-active-p
   #:chain-config-homestead-p
   #:chain-config-dao-fork-p
   #:chain-config-eip150-p
   #:chain-config-eip155-p
   #:chain-config-eip158-p
   #:chain-config-byzantium-p
   #:chain-config-constantinople-p
   #:chain-config-petersburg-p
   #:chain-config-istanbul-p
   #:chain-config-berlin-p
   #:chain-config-london-p
   #:chain-config-shanghai-p
   #:chain-config-cancun-p
   #:chain-config-prague-p
   #:chain-config-osaka-p
   #:chain-config-bpo1-p
   #:chain-config-bpo2-p
   #:chain-config-bpo3-p
   #:chain-config-bpo4-p
   #:chain-config-bpo5-p
   #:chain-config-amsterdam-p
   #:chain-config-ubt-p
   #:chain-config-ubt-genesis-p
   #:chain-config-expanded-blob-schedule-p
   #:chain-config-blob-schedule
   #:parse-json
   #:chain-config-from-genesis-config
   #:chain-config-from-genesis-json-string
   #:chain-config-from-genesis-json-file
   #:genesis-alloc-from-genesis-object
   #:genesis-alloc-from-genesis-json-string
   #:genesis-alloc-from-genesis-json-file
   #:genesis-expected-state-root-from-genesis-object
   #:genesis-expected-state-root-from-genesis-json-string
   #:genesis-expected-state-root-from-genesis-json-file
   #:genesis-header-from-genesis-object
   #:genesis-header-from-genesis-json-string
   #:genesis-header-from-genesis-json-file
   #:genesis-block-from-genesis-header
   #:genesis-block-from-genesis-object
   #:genesis-block-from-genesis-json-string
   #:genesis-block-from-genesis-json-file
   #:chain-config-rules
   #:chain-rules
   #:make-chain-rules
   #:chain-rules-chain-id
   #:chain-rules-homestead-p
   #:chain-rules-eip150-p
   #:chain-rules-eip155-p
   #:chain-rules-eip158-p
   #:chain-rules-byzantium-p
   #:chain-rules-constantinople-p
   #:chain-rules-petersburg-p
   #:chain-rules-istanbul-p
   #:chain-rules-berlin-p
   #:chain-rules-london-p
   #:chain-rules-shanghai-p
   #:chain-rules-cancun-p
   #:chain-rules-prague-p
   #:chain-rules-osaka-p
   #:chain-rules-bpo1-p
   #:chain-rules-bpo2-p
   #:chain-rules-bpo3-p
   #:chain-rules-bpo4-p
   #:chain-rules-bpo5-p
   #:chain-rules-amsterdam-p
   #:chain-rules-ubt-p
   #:chain-rules-blob-schedule-target-gas
   #:chain-rules-blob-schedule-max-gas
   #:chain-rules-blob-schedule-update-fraction
   #:chain-rules-expanded-blob-schedule-p
   #:chain-rules-blob-schedule
   #:chain-rules-transaction-type-supported-p
   #:state-account
   #:make-state-account
   #:state-account-nonce
   #:state-account-balance
   #:state-account-storage-root
   #:state-account-code-hash
   #:state-account-rlp
   #:state-account-hash
   #:legacy-transaction
   #:make-legacy-transaction
   #:legacy-transaction-nonce
   #:legacy-transaction-gas-price
   #:legacy-transaction-gas-limit
   #:legacy-transaction-to
   #:legacy-transaction-value
   #:legacy-transaction-data
   #:legacy-transaction-v
   #:legacy-transaction-r
   #:legacy-transaction-s
   #:legacy-transaction-rlp
   #:legacy-transaction-hash
   #:legacy-transaction-signing-payload
   #:legacy-transaction-signing-hash
   #:legacy-transaction-protected-p
   #:legacy-transaction-chain-id
   #:legacy-transaction-sender
   #:access-list-entry
   #:make-access-list-entry
   #:access-list-entry-address
   #:access-list-entry-storage-keys
   #:access-list-storage-key-count
   #:access-list-transaction
   #:make-access-list-transaction
   #:access-list-transaction-chain-id
   #:access-list-transaction-y-parity
   #:access-list-transaction-r
   #:access-list-transaction-s
   #:access-list-transaction-encoding
   #:access-list-transaction-hash
   #:access-list-transaction-signing-payload
   #:access-list-transaction-signing-hash
   #:access-list-transaction-sender
   #:dynamic-fee-transaction
   #:make-dynamic-fee-transaction
   #:dynamic-fee-transaction-max-priority-fee-per-gas
   #:dynamic-fee-transaction-max-fee-per-gas
   #:dynamic-fee-transaction-chain-id
   #:dynamic-fee-transaction-y-parity
   #:dynamic-fee-transaction-r
   #:dynamic-fee-transaction-s
   #:dynamic-fee-transaction-encoding
   #:dynamic-fee-transaction-hash
   #:dynamic-fee-transaction-signing-payload
   #:dynamic-fee-transaction-signing-hash
   #:dynamic-fee-transaction-sender
   #:blob-transaction
   #:make-blob-transaction
   #:blob-transaction-chain-id
   #:blob-transaction-y-parity
   #:blob-transaction-r
   #:blob-transaction-s
   #:blob-transaction-max-priority-fee-per-gas
   #:blob-transaction-max-fee-per-gas
   #:blob-transaction-blob-versioned-hashes
   #:blob-transaction-max-fee-per-blob-gas
   #:blob-transaction-encoding
   #:blob-transaction-hash
   #:blob-transaction-signing-hash
   #:blob-transaction-sender
   #:blob-sidecar
   #:make-blob-sidecar
   #:blob-sidecar-blobs
   #:blob-sidecar-commitments
   #:blob-sidecar-proofs
   #:blob-sidecar-versioned-hashes
   #:set-code-authorization
   #:make-set-code-authorization
   #:set-code-authorization-chain-id
   #:set-code-authorization-address
   #:set-code-authorization-nonce
   #:set-code-authorization-y-parity
   #:set-code-authorization-r
   #:set-code-authorization-s
   #:set-code-authorization-signing-hash
   #:set-code-authorization-authority
   #:set-code-delegation-code
   #:set-code-delegation-target
   #:set-code-transaction
   #:make-set-code-transaction
   #:set-code-transaction-chain-id
   #:set-code-transaction-y-parity
   #:set-code-transaction-r
   #:set-code-transaction-s
   #:set-code-transaction-encoding
   #:set-code-transaction-hash
   #:set-code-transaction-signing-hash
   #:set-code-transaction-sender
   #:transaction-encoding
   #:transaction-hash
   #:transaction-sender
   #:transaction-nonce
   #:transaction-gas-limit
   #:transaction-to
   #:transaction-value
   #:transaction-data
   #:transaction-access-list
   #:transaction-authorization-list
   #:transaction-type
   #:validate-transaction-type-for-config
   #:transaction-blob-versioned-hashes
   #:transaction-blob-gas-used
   #:transaction-max-priority-fee-per-gas
   #:transaction-max-fee-per-gas
   #:validate-1559-transaction-fees
   #:transaction-effective-gas-price
   #:transaction-priority-fee-per-gas
   #:block-header
   #:make-block-header
   #:block-header-parent-hash
   #:block-header-ommers-hash
   #:block-header-beneficiary
   #:block-header-state-root
   #:block-header-transactions-root
   #:block-header-receipts-root
   #:block-header-logs-bloom
   #:block-header-difficulty
   #:block-header-number
   #:block-header-gas-limit
   #:block-header-gas-used
   #:block-header-timestamp
   #:block-header-extra-data
   #:block-header-mix-hash
   #:block-header-nonce
   #:block-header-base-fee-per-gas
   #:block-header-withdrawals-root
   #:block-header-blob-gas-used
   #:block-header-excess-blob-gas
   #:block-header-parent-beacon-root
   #:block-header-requests-hash
   #:block-header-block-access-list-hash
   #:block-header-slot-number
   #:block-header-rlp
   #:block-header-hash
   #:ethereum-block
   #:make-block
   #:block-header
   #:block-transactions
   #:block-ommers
   #:block-withdrawals
   #:block-withdrawals-present-p
   #:block-requests
   #:block-requests-present-p
   #:block-block-access-list
   #:block-block-access-list-present-p
   #:block-encoded-block-access-list
   #:block-hash
   #:execution-requests-hash
   #:block-access-account
   #:make-block-access-account
   #:block-access-account-address
   #:block-access-account-storage-writes
   #:block-access-account-storage-reads
   #:block-access-account-balance-changes
   #:block-access-account-nonce-changes
   #:block-access-account-code-changes
   #:block-access-storage-write
   #:make-block-access-storage-write
   #:block-access-storage-write-tx-index
   #:block-access-storage-write-value-after
   #:block-access-slot-writes
   #:make-block-access-slot-writes
   #:block-access-slot-writes-slot
   #:block-access-slot-writes-accesses
   #:block-access-balance-change
   #:make-block-access-balance-change
   #:block-access-balance-change-tx-index
   #:block-access-balance-change-balance
   #:block-access-nonce-change
   #:make-block-access-nonce-change
   #:block-access-nonce-change-tx-index
   #:block-access-nonce-change-nonce
   #:block-access-code-change
   #:make-block-access-code-change
   #:block-access-code-change-tx-index
   #:block-access-code-change-code
   #:block-access-account-rlp
   #:block-access-list-rlp
   #:block-access-list-from-rlp
   #:block-access-list-rlp-hash
   #:block-access-list-hash
   #:block-access-list-item-count
   #:block-validation-error
   #:block-validation-error-message
   #:expected-base-fee-per-gas
   #:validate-block-base-fee
   #:validate-gas-limit-delta
   #:adjusted-parent-gas-limit-for-1559
   #:validate-block-blob-gas-fields
   #:expected-excess-blob-gas
   #:fake-exponential
   #:blob-base-fee
   #:block-header-blob-base-fee
   #:validate-block-excess-blob-gas
   #:block-header-cancun-fields-present-p
   #:validate-block-cancun-fields
   #:validate-block-withdrawals-field
   #:validate-block-requests-hash-field
   #:block-header-amsterdam-fields-present-p
   #:validate-block-amsterdam-fields
   #:validate-block-amsterdam-slot-number
   #:validate-block-header-basics
   #:validate-block-header-against-config
   #:validate-blob-versioned-hash
   #:validate-blob-transaction-fields
   #:validate-blob-transaction-fee-cap
   #:validate-blob-sidecar-fields
   #:validate-withdrawal-fields
   #:validate-withdrawal-list-fields
   #:validate-execution-request-fields
   #:validate-execution-request-list-fields
   #:validate-block-access-account-fields
   #:validate-block-access-list-fields
   #:validate-block-transactions-against-config
   #:validate-block-body-against-config
   #:validate-block-against-config
   #:validate-block-body-roots
   #:blob-gas-used
   #:receipts-gas-used
   #:validate-block-execution-roots
   #:withdrawal
   #:make-withdrawal
   #:withdrawal-index
   #:withdrawal-validator-index
   #:withdrawal-address
   #:withdrawal-amount
   #:withdrawal-rlp
   #:withdrawal-list-root
   #:log-entry
   #:make-log-entry
   #:log-entry-address
   #:log-entry-topics
   #:log-entry-data
   #:log-entry-rlp-object
   #:bloom
   #:make-bloom
   #:bloom-bytes
   #:bloom-add
   #:bloom-contains-p
   #:receipt
   #:make-receipt
   #:receipt-status
   #:receipt-cumulative-gas-used
   #:receipt-logs
   #:receipt-rlp
   #:transaction-receipt-encoding
   #:receipt-bloom
   #:derive-list-root
   #:transaction-list-root
   #:receipt-list-root
   #:transaction-receipt-list-root)
  (:import-from #:ethereum-lisp.evm
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:execute-bytecode)
  (:import-from #:ethereum-lisp.state
   #:state-db
   #:make-state-db
   #:state-db-get-account
   #:state-db-set-account
   #:state-db-set-code
   #:state-db-get-code
   #:state-db-get-code-hash
   #:state-db-copy
   #:state-db-restore
   #:state-db-set-storage
   #:state-db-get-storage
   #:state-db-root
   #:state-db-root-hex
   #:apply-genesis-account
   #:apply-genesis-alloc
   #:state-db-from-genesis-alloc
   #:state-db-from-genesis-json-string
   #:state-db-from-genesis-json-file
   #:genesis-state-root-from-genesis-alloc
   #:genesis-state-root-from-genesis-json-string
   #:genesis-state-root-from-genesis-json-file
   #:validate-genesis-state-root
   #:validate-genesis-json-state-root
   #:genesis-header-from-state-genesis-object
   #:genesis-header-from-state-genesis-json-string
   #:genesis-header-from-state-genesis-json-file
   #:genesis-block-from-state-genesis-object
   #:genesis-block-from-state-genesis-json-string
   #:genesis-block-from-state-genesis-json-file
   #:+wei-per-gwei+
   #:state-db-add-balance
   #:apply-withdrawal
   #:apply-withdrawals
   #:transaction-validation-error
   #:transaction-intrinsic-gas
   #:apply-legacy-transaction
   #:apply-message
   #:apply-message-list
   #:execution-result
   #:make-execution-result
   #:execution-result-receipts
   #:execution-result-state-root
   #:execution-result-transactions-root
   #:execution-result-receipts-root
   #:execute-legacy-transactions)
  (:import-from #:ethereum-lisp.execution
   #:apply-legacy-message
   #:apply-signed-message
   #:apply-signed-message-list
   #:execute-legacy-messages
   #:execute-signed-messages
   #:execute-legacy-block
   #:execute-signed-block)
  (:export
   #:byte-vector
   #:byte-vector-p
   #:make-byte-vector
   #:ensure-byte-vector
   #:bytes=
   #:concat-bytes
   #:integer-to-minimal-bytes
   #:bytes-to-integer
   #:ascii-to-bytes
   #:bytes-to-ascii
   #:bytes-to-hex
   #:hex-to-bytes
   #:quantity-to-hex
   #:hex-to-quantity
   #:rlp-error
   #:rlp-list
   #:rlp-list-p
   #:rlp-list-items
   #:make-rlp-list
   #:rlp-encode
   #:rlp-decode
   #:rlp-decode-one
   #:+uint256-max+
   #:uint256-p
   #:address
   #:address-p
   #:address-bytes
   #:make-address
   #:address-from-hex
   #:address-to-hex
   #:zero-address
   #:hash32
   #:hash32-p
   #:hash32-bytes
   #:make-hash32
   #:hash32-from-hex
   #:hash32-to-hex
   #:zero-hash32
   #:keccak-256
   #:keccak-256-hash
   #:keccak-256-hex
   #:sha256
   #:sha256-hash
   #:sha256-hex
   #:ripemd160
   #:ripemd160-hex
   #:secp256k1-recover-public-key
   #:secp256k1-recover-address
   #:secp256k1-valid-signature-values-p
   #:+kzg-commitment-size+
   #:+kzg-commitment-version+
   #:kzg-commitment-to-versioned-hash
   #:+empty-code-hash+
   #:+empty-trie-hash+
   #:+terminator-nibble+
   #:has-terminator-p
   #:keybytes-to-nibbles
   #:nibbles-to-keybytes
   #:hex-prefix-encode
   #:hex-prefix-decode
   #:common-prefix-length
   #:mpt
   #:make-mpt
   #:mpt-put
   #:mpt-get
   #:mpt-root-hash
   #:mpt-root-hex
   #:mpt-root-node
   #:+empty-ommers-hash+
   #:+initial-base-fee+
   #:+base-fee-elasticity-multiplier+
   #:+base-fee-change-denominator+
   #:+blob-gas-per-blob+
   #:+blob-byte-size+
   #:+kzg-proof-size+
   #:+target-blobs-per-block+
   #:+max-blobs-per-block+
   #:+osaka-target-blobs-per-block+
   #:+osaka-max-blobs-per-block+
   #:+bpo1-target-blobs-per-block+
   #:+bpo1-max-blobs-per-block+
   #:+bpo2-target-blobs-per-block+
   #:+bpo2-max-blobs-per-block+
   #:+bpo3-target-blobs-per-block+
   #:+bpo3-max-blobs-per-block+
   #:+bpo4-target-blobs-per-block+
   #:+bpo4-max-blobs-per-block+
   #:+min-blobs-per-transaction+
   #:+min-blob-gas-price+
   #:+blob-base-fee-update-fraction+
   #:+osaka-blob-base-fee-update-fraction+
   #:+bpo1-blob-base-fee-update-fraction+
   #:+bpo2-blob-base-fee-update-fraction+
   #:+bpo3-blob-base-fee-update-fraction+
   #:+bpo4-blob-base-fee-update-fraction+
   #:+blob-base-cost+
   #:+maximum-extra-data-size+
   #:+block-access-list-max-code-size+
   #:+block-access-list-amsterdam-max-code-size+
   #:+block-access-list-item-gas-cost+
   #:+gas-limit-bound-divisor+
   #:+minimum-gas-limit+
   #:+genesis-gas-limit+
   #:+genesis-difficulty+
   #:blob-schedule-entry
   #:make-blob-schedule-entry
   #:blob-schedule-entry-timestamp
   #:blob-schedule-entry-target-blobs
   #:blob-schedule-entry-max-blobs
   #:blob-schedule-entry-update-fraction
   #:genesis-account
   #:make-genesis-account
   #:genesis-account-address
   #:genesis-account-balance
   #:genesis-account-nonce
   #:genesis-account-code
   #:genesis-account-storage
   #:chain-config
   #:make-chain-config
   #:chain-config-chain-id
   #:chain-config-homestead-block
   #:chain-config-dao-fork-block
   #:chain-config-dao-fork-support
   #:chain-config-eip150-block
   #:chain-config-eip155-block
   #:chain-config-eip158-block
   #:chain-config-byzantium-block
   #:chain-config-constantinople-block
   #:chain-config-petersburg-block
   #:chain-config-istanbul-block
   #:chain-config-muir-glacier-block
   #:chain-config-berlin-block
   #:chain-config-london-block
   #:chain-config-arrow-glacier-block
   #:chain-config-gray-glacier-block
   #:chain-config-shanghai-time
   #:chain-config-cancun-time
   #:chain-config-prague-time
   #:chain-config-osaka-time
   #:chain-config-bpo1-time
   #:chain-config-bpo2-time
   #:chain-config-bpo3-time
   #:chain-config-bpo4-time
   #:chain-config-bpo5-time
   #:chain-config-amsterdam-time
   #:chain-config-ubt-time
   #:chain-config-enable-ubt-at-genesis-p
   #:chain-config-terminal-total-difficulty
   #:chain-config-terminal-total-difficulty-passed
   #:chain-config-merge-netsplit-block
   #:chain-config-deposit-contract-address
   #:chain-config-custom-blob-schedule
   #:fork-block-active-p
   #:fork-time-active-p
   #:chain-config-homestead-p
   #:chain-config-dao-fork-p
   #:chain-config-eip150-p
   #:chain-config-eip155-p
   #:chain-config-eip158-p
   #:chain-config-byzantium-p
   #:chain-config-constantinople-p
   #:chain-config-petersburg-p
   #:chain-config-istanbul-p
   #:chain-config-berlin-p
   #:chain-config-london-p
   #:chain-config-shanghai-p
   #:chain-config-cancun-p
   #:chain-config-prague-p
   #:chain-config-osaka-p
   #:chain-config-bpo1-p
   #:chain-config-bpo2-p
   #:chain-config-bpo3-p
   #:chain-config-bpo4-p
   #:chain-config-bpo5-p
   #:chain-config-amsterdam-p
   #:chain-config-ubt-p
   #:chain-config-ubt-genesis-p
   #:chain-config-expanded-blob-schedule-p
   #:chain-config-blob-schedule
   #:parse-json
   #:chain-config-from-genesis-config
   #:chain-config-from-genesis-json-string
   #:chain-config-from-genesis-json-file
   #:genesis-alloc-from-genesis-object
   #:genesis-alloc-from-genesis-json-string
   #:genesis-alloc-from-genesis-json-file
   #:genesis-expected-state-root-from-genesis-object
   #:genesis-expected-state-root-from-genesis-json-string
   #:genesis-expected-state-root-from-genesis-json-file
   #:genesis-header-from-genesis-object
   #:genesis-header-from-genesis-json-string
   #:genesis-header-from-genesis-json-file
   #:genesis-block-from-genesis-header
   #:genesis-block-from-genesis-object
   #:genesis-block-from-genesis-json-string
   #:genesis-block-from-genesis-json-file
   #:chain-config-rules
   #:chain-rules
   #:make-chain-rules
   #:chain-rules-chain-id
   #:chain-rules-homestead-p
   #:chain-rules-eip150-p
   #:chain-rules-eip155-p
   #:chain-rules-eip158-p
   #:chain-rules-byzantium-p
   #:chain-rules-constantinople-p
   #:chain-rules-petersburg-p
   #:chain-rules-istanbul-p
   #:chain-rules-berlin-p
   #:chain-rules-london-p
   #:chain-rules-shanghai-p
   #:chain-rules-cancun-p
   #:chain-rules-prague-p
   #:chain-rules-osaka-p
   #:chain-rules-bpo1-p
   #:chain-rules-bpo2-p
   #:chain-rules-bpo3-p
   #:chain-rules-bpo4-p
   #:chain-rules-bpo5-p
   #:chain-rules-amsterdam-p
   #:chain-rules-ubt-p
   #:chain-rules-blob-schedule-target-gas
   #:chain-rules-blob-schedule-max-gas
   #:chain-rules-blob-schedule-update-fraction
   #:chain-rules-expanded-blob-schedule-p
   #:chain-rules-blob-schedule
   #:chain-rules-transaction-type-supported-p
   #:state-account
   #:make-state-account
   #:state-account-nonce
   #:state-account-balance
   #:state-account-storage-root
   #:state-account-code-hash
   #:state-account-rlp
   #:state-account-hash
   #:legacy-transaction
   #:make-legacy-transaction
   #:legacy-transaction-nonce
   #:legacy-transaction-gas-price
   #:legacy-transaction-gas-limit
   #:legacy-transaction-to
   #:legacy-transaction-value
   #:legacy-transaction-data
   #:legacy-transaction-v
   #:legacy-transaction-r
   #:legacy-transaction-s
   #:legacy-transaction-rlp
   #:legacy-transaction-hash
   #:legacy-transaction-signing-payload
   #:legacy-transaction-signing-hash
   #:legacy-transaction-protected-p
   #:legacy-transaction-chain-id
   #:legacy-transaction-sender
   #:access-list-entry
   #:make-access-list-entry
   #:access-list-entry-address
   #:access-list-entry-storage-keys
   #:access-list-storage-key-count
   #:access-list-transaction
   #:make-access-list-transaction
   #:access-list-transaction-chain-id
   #:access-list-transaction-y-parity
   #:access-list-transaction-r
   #:access-list-transaction-s
   #:access-list-transaction-encoding
   #:access-list-transaction-hash
   #:access-list-transaction-signing-payload
   #:access-list-transaction-signing-hash
   #:access-list-transaction-sender
   #:dynamic-fee-transaction
   #:make-dynamic-fee-transaction
   #:dynamic-fee-transaction-max-priority-fee-per-gas
   #:dynamic-fee-transaction-max-fee-per-gas
   #:dynamic-fee-transaction-chain-id
   #:dynamic-fee-transaction-y-parity
   #:dynamic-fee-transaction-r
   #:dynamic-fee-transaction-s
   #:dynamic-fee-transaction-encoding
   #:dynamic-fee-transaction-hash
   #:dynamic-fee-transaction-signing-payload
   #:dynamic-fee-transaction-signing-hash
   #:dynamic-fee-transaction-sender
   #:blob-transaction
   #:make-blob-transaction
   #:blob-transaction-chain-id
   #:blob-transaction-y-parity
   #:blob-transaction-r
   #:blob-transaction-s
   #:blob-transaction-max-priority-fee-per-gas
   #:blob-transaction-max-fee-per-gas
   #:blob-transaction-blob-versioned-hashes
   #:blob-transaction-max-fee-per-blob-gas
   #:blob-transaction-encoding
   #:blob-transaction-hash
   #:blob-transaction-signing-hash
   #:blob-transaction-sender
   #:blob-sidecar
   #:make-blob-sidecar
   #:blob-sidecar-blobs
   #:blob-sidecar-commitments
   #:blob-sidecar-proofs
   #:blob-sidecar-versioned-hashes
   #:set-code-authorization
   #:make-set-code-authorization
   #:set-code-authorization-chain-id
   #:set-code-authorization-address
   #:set-code-authorization-nonce
   #:set-code-authorization-y-parity
   #:set-code-authorization-r
   #:set-code-authorization-s
   #:set-code-authorization-signing-hash
   #:set-code-authorization-authority
   #:set-code-delegation-code
   #:set-code-delegation-target
   #:set-code-transaction
   #:make-set-code-transaction
   #:set-code-transaction-chain-id
   #:set-code-transaction-y-parity
   #:set-code-transaction-r
   #:set-code-transaction-s
   #:set-code-transaction-encoding
   #:set-code-transaction-hash
   #:set-code-transaction-signing-hash
   #:set-code-transaction-sender
   #:transaction-encoding
   #:transaction-hash
   #:transaction-sender
   #:transaction-nonce
   #:transaction-gas-limit
   #:transaction-to
   #:transaction-value
   #:transaction-data
   #:transaction-access-list
   #:transaction-authorization-list
   #:transaction-type
   #:validate-transaction-type-for-config
   #:transaction-blob-versioned-hashes
   #:transaction-blob-gas-used
   #:transaction-max-priority-fee-per-gas
   #:transaction-max-fee-per-gas
   #:validate-1559-transaction-fees
   #:transaction-effective-gas-price
   #:transaction-priority-fee-per-gas
   #:block-header
   #:make-block-header
   #:block-header-parent-hash
   #:block-header-ommers-hash
   #:block-header-beneficiary
   #:block-header-state-root
   #:block-header-transactions-root
   #:block-header-receipts-root
   #:block-header-logs-bloom
   #:block-header-difficulty
   #:block-header-number
   #:block-header-gas-limit
   #:block-header-gas-used
   #:block-header-timestamp
   #:block-header-extra-data
   #:block-header-mix-hash
   #:block-header-nonce
   #:block-header-base-fee-per-gas
   #:block-header-withdrawals-root
   #:block-header-blob-gas-used
   #:block-header-excess-blob-gas
   #:block-header-parent-beacon-root
   #:block-header-requests-hash
   #:block-header-block-access-list-hash
   #:block-header-slot-number
   #:block-header-rlp
   #:block-header-hash
   #:ethereum-block
   #:make-block
   #:block-header
   #:block-transactions
   #:block-ommers
   #:block-withdrawals
   #:block-withdrawals-present-p
   #:block-requests
   #:block-requests-present-p
   #:block-block-access-list
   #:block-block-access-list-present-p
   #:block-encoded-block-access-list
   #:block-hash
   #:execution-requests-hash
   #:block-access-account
   #:make-block-access-account
   #:block-access-account-address
   #:block-access-account-storage-writes
   #:block-access-account-storage-reads
   #:block-access-account-balance-changes
   #:block-access-account-nonce-changes
   #:block-access-account-code-changes
   #:block-access-storage-write
   #:make-block-access-storage-write
   #:block-access-storage-write-tx-index
   #:block-access-storage-write-value-after
   #:block-access-slot-writes
   #:make-block-access-slot-writes
   #:block-access-slot-writes-slot
   #:block-access-slot-writes-accesses
   #:block-access-balance-change
   #:make-block-access-balance-change
   #:block-access-balance-change-tx-index
   #:block-access-balance-change-balance
   #:block-access-nonce-change
   #:make-block-access-nonce-change
   #:block-access-nonce-change-tx-index
   #:block-access-nonce-change-nonce
   #:block-access-code-change
   #:make-block-access-code-change
   #:block-access-code-change-tx-index
   #:block-access-code-change-code
   #:block-access-account-rlp
   #:block-access-list-rlp
   #:block-access-list-from-rlp
   #:block-access-list-rlp-hash
   #:block-access-list-hash
   #:block-access-list-item-count
   #:block-validation-error
   #:block-validation-error-message
   #:expected-base-fee-per-gas
   #:validate-block-base-fee
   #:validate-gas-limit-delta
   #:adjusted-parent-gas-limit-for-1559
   #:validate-block-blob-gas-fields
   #:expected-excess-blob-gas
   #:fake-exponential
   #:blob-base-fee
   #:block-header-blob-base-fee
   #:validate-block-excess-blob-gas
   #:block-header-cancun-fields-present-p
   #:validate-block-cancun-fields
   #:validate-block-withdrawals-field
   #:validate-block-requests-hash-field
   #:block-header-amsterdam-fields-present-p
   #:validate-block-amsterdam-fields
   #:validate-block-amsterdam-slot-number
   #:validate-block-header-basics
   #:validate-block-header-against-config
   #:validate-blob-versioned-hash
   #:validate-blob-transaction-fields
   #:validate-blob-transaction-fee-cap
   #:validate-blob-sidecar-fields
   #:validate-withdrawal-fields
   #:validate-withdrawal-list-fields
   #:validate-execution-request-fields
   #:validate-execution-request-list-fields
   #:validate-block-access-account-fields
   #:validate-block-access-list-fields
   #:validate-block-transactions-against-config
   #:validate-block-body-against-config
   #:validate-block-against-config
   #:validate-block-body-roots
   #:blob-gas-used
   #:receipts-gas-used
   #:validate-block-execution-roots
   #:withdrawal
   #:make-withdrawal
   #:withdrawal-index
   #:withdrawal-validator-index
   #:withdrawal-address
   #:withdrawal-amount
   #:withdrawal-rlp
   #:withdrawal-list-root
   #:log-entry
   #:make-log-entry
   #:log-entry-address
   #:log-entry-topics
   #:log-entry-data
   #:log-entry-rlp-object
   #:bloom
   #:make-bloom
   #:bloom-bytes
   #:bloom-add
   #:bloom-contains-p
   #:receipt
   #:make-receipt
   #:receipt-status
   #:receipt-cumulative-gas-used
   #:receipt-logs
   #:receipt-rlp
   #:transaction-receipt-encoding
   #:receipt-bloom
   #:derive-list-root
   #:transaction-list-root
   #:receipt-list-root
   #:transaction-receipt-list-root
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:execute-bytecode
   #:state-db
   #:make-state-db
   #:state-db-get-account
   #:state-db-set-account
   #:state-db-set-code
   #:state-db-get-code
   #:state-db-get-code-hash
   #:state-db-copy
   #:state-db-restore
   #:state-db-set-storage
   #:state-db-get-storage
   #:state-db-root
   #:state-db-root-hex
   #:apply-genesis-account
   #:apply-genesis-alloc
   #:state-db-from-genesis-alloc
   #:state-db-from-genesis-json-string
   #:state-db-from-genesis-json-file
   #:genesis-state-root-from-genesis-alloc
   #:genesis-state-root-from-genesis-json-string
   #:genesis-state-root-from-genesis-json-file
   #:validate-genesis-state-root
   #:validate-genesis-json-state-root
   #:genesis-header-from-state-genesis-object
   #:genesis-header-from-state-genesis-json-string
   #:genesis-header-from-state-genesis-json-file
   #:genesis-block-from-state-genesis-object
   #:genesis-block-from-state-genesis-json-string
   #:genesis-block-from-state-genesis-json-file
   #:+wei-per-gwei+
   #:state-db-add-balance
   #:apply-withdrawal
   #:apply-withdrawals
   #:transaction-validation-error
   #:transaction-intrinsic-gas
   #:apply-legacy-transaction
   #:apply-message
   #:apply-message-list
   #:execution-result
   #:make-execution-result
   #:execution-result-receipts
   #:execution-result-state-root
   #:execution-result-transactions-root
   #:execution-result-receipts-root
   #:execute-legacy-transactions
   #:apply-legacy-message
   #:apply-signed-message
   #:apply-signed-message-list
   #:execute-legacy-messages
   #:execute-signed-messages
   #:execute-legacy-block
   #:execute-signed-block))
