(defpackage #:ethereum-lisp.chain-store.model
  (:use #:cl
        #:ethereum-lisp.types
        #:ethereum-lisp.validation)
  (:export
   #:chain-store-checkpoint
   #:chain-store-checkpoint-p
   #:make-chain-store-checkpoint
   #:chain-store-checkpoint-label
   #:chain-store-checkpoint-block-hash
   #:engine-transaction-location
   #:engine-transaction-location-p
   #:make-engine-transaction-location
   #:engine-transaction-location-block
   #:engine-transaction-location-index
   #:engine-transaction-location-transaction
   #:engine-transaction-location-receipt
   #:engine-transaction-location-log-index-start
   #:engine-blob-and-proofs
   #:engine-blob-and-proofs-p
   #:make-engine-blob-and-proofs
   #:engine-blob-and-proofs-blob
   #:engine-blob-and-proofs-commitment
   #:engine-blob-and-proofs-proof
   #:engine-blob-and-proofs-cell-proofs
   #:engine-log-filter
   #:engine-log-filter-p
   #:make-engine-log-filter
   #:engine-log-filter-criteria
   #:engine-log-filter-last-block-number
   #:engine-log-filter-pending-changes
   #:engine-log-filter-block-hash-p
   #:engine-log-filter-block-hash-consumed-p
   #:engine-log-filter-change
   #:engine-log-filter-change-p
   #:make-engine-log-filter-change
   #:engine-log-filter-change-block
   #:engine-log-filter-change-removed-p
   #:engine-block-filter
   #:engine-block-filter-p
   #:make-engine-block-filter
   #:engine-block-filter-last-block-number
   #:engine-block-filter-hashes
   #:engine-pending-transaction-filter
   #:engine-pending-transaction-filter-p
   #:make-engine-pending-transaction-filter
   #:engine-pending-transaction-filter-hashes
   #:engine-pending-transaction-filter-record-hash
   #:engine-block-filter-record-hash
   #:engine-payload-store-key))

(defpackage #:ethereum-lisp.chain-store.state
  (:use #:cl
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-store.model)
  (:export
   #:memory-chain-store
   #:memory-chain-store-p
   #:make-memory-chain-store
   #:chain-store-component
   #:chain-store-require-memory-store
   #:memory-chain-store-blocks
   #:memory-chain-store-number-blocks
   #:memory-chain-store-canonical-hashes
   #:memory-chain-store-transaction-locations
   #:memory-chain-store-account-balances
   #:memory-chain-store-account-nonces
   #:memory-chain-store-account-codes
   #:memory-chain-store-account-storage
   #:memory-chain-store-head-number
   #:memory-chain-store-state-blocks
   #:memory-chain-store-remote-blocks
   #:memory-chain-store-invalid-tipsets
   #:memory-chain-store-prepared-payloads
   #:memory-chain-store-blob-sidecars
   #:memory-chain-store-log-filters
   #:memory-chain-store-next-log-filter-id
   #:memory-chain-store-head-checkpoint
   #:memory-chain-store-safe-checkpoint
   #:memory-chain-store-finalized-checkpoint))

(defpackage #:ethereum-lisp.node-state
  (:use #:cl
        #:ethereum-lisp.chain-store.state
        #:ethereum-lisp.txpool.index)
  (:export
   #:engine-payload-memory-store
   #:engine-payload-memory-store-p
   #:make-engine-payload-memory-store
   #:engine-payload-memory-store-chain-store
   #:engine-payload-memory-store-txpool))

(defpackage #:ethereum-lisp.chain-store
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.engine-payloads
        #:ethereum-lisp.chain-store.model
        #:ethereum-lisp.chain-store.state)
  (:export
   #:engine-payload-store-copy-table
   #:engine-payload-store-copy-checkpoint
   #:engine-payload-store-copy-filter
   #:engine-payload-store-copy-filter-table
   #:engine-payload-store-copy-blob-and-proofs
   #:engine-payload-store-copy-blob-sidecar-table
   #:maybe-copy-hash32
   #:maybe-copy-address
   #:engine-payload-store-copy-block-header
   #:engine-payload-store-copy-log-entry
   #:engine-payload-store-copy-receipt
   #:engine-payload-store-copy-block
   #:engine-payload-store-copy-block-table
   #:engine-payload-store-copy-prepared-payload
   #:engine-payload-store-copy-prepared-payload-table
   #:engine-payload-store-copy-transaction
   #:engine-payload-store-copy-transaction-location
   #:engine-payload-store-copy-transaction-location-table
   #:copy-memory-chain-store
   #:engine-payload-store-notify-block-filters
   #:engine-log-filter-record-change
   #:engine-payload-store-notify-log-filters
   #:engine-payload-store-notify-pending-transaction-filters
   #:engine-payload-store-put-log-filter
   #:engine-payload-store-put-block-filter
   #:engine-payload-store-put-pending-transaction-filter
   #:engine-payload-store-log-filter
   #:engine-payload-store-uninstall-log-filter
   #:engine-payload-store-remote-block
   #:engine-payload-store-put-remote-block
   #:engine-payload-store-remove-remote-block
   #:engine-payload-store-prune-prepared-payloads-for-block
   #:engine-payload-store-mark-invalid
   #:engine-payload-store-invalid-block
   #:engine-payload-id-key
   #:engine-payload-id-to-hex
   #:engine-payload-store-put-prepared-payload
   #:engine-payload-store-prepared-payload
   #:chain-store-put-prepared-payload
   #:chain-store-prepared-payload
   #:engine-payload-store-put-blob-sidecar
   #:engine-payload-store-blob-and-proofs-v1
   #:engine-payload-store-blob-and-proofs-v2
   #:memory-chain-store-put-block
   #:engine-payload-store-known-block
   #:engine-payload-store-checkpoint-number
   #:engine-payload-store-head-number
   #:engine-payload-store-block-tag-number
   #:engine-payload-store-forkchoice-checkpoint-hash
   #:engine-payload-store-update-forkchoice-checkpoints
   #:engine-payload-store-state-available-p
   #:chain-store-state-available-p
   #:engine-payload-store-prune-state-snapshot
   #:chain-store-prune-state-before
   #:engine-payload-store-account-key
   #:engine-payload-store-account-storage-key
   #:engine-payload-store-put-account-balance
   #:engine-payload-store-account-balance
   #:engine-payload-store-put-account-nonce
   #:engine-payload-store-account-nonce
   #:engine-payload-store-put-account-code
   #:engine-payload-store-account-code
   #:engine-payload-store-put-account-storage
   #:engine-payload-store-account-storage
   #:chain-store-put-account-balance
   #:chain-store-account-balance
   #:chain-store-put-account-nonce
   #:chain-store-account-nonce
   #:chain-store-put-account-code
   #:chain-store-account-code
   #:chain-store-put-account-storage
   #:chain-store-account-storage
   #:engine-payload-store-account-storage-entries
   #:chain-store-for-each-account
   #:engine-payload-store-canonical-parent-p
   #:engine-payload-store-block-by-number
   #:engine-payload-store-canonical-hash
   #:engine-payload-store-canonical-block-p
   #:engine-payload-store-ancestor-p
   #:engine-payload-store-put-transaction-location
   #:engine-payload-store-index-block-transactions
   #:engine-payload-store-remove-block-transaction-locations
   #:engine-payload-store-transaction-location
   #:chain-store-put-block
   #:chain-store-known-block
   #:chain-store-block-by-number
   #:chain-store-canonical-hash
   #:chain-store-head-number
   #:chain-store-block-tag-number
   #:chain-store-latest-block
   #:chain-store-transaction-location
   #:chain-store-block-receipts
   #:chain-store-update-forkchoice-checkpoints
   #:chain-store-head-checkpoint
   #:chain-store-safe-checkpoint
   #:chain-store-finalized-checkpoint
   #:chain-store-head-block
   #:chain-store-safe-block
   #:chain-store-finalized-block))
