(defpackage #:ethereum-lisp.state
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.rlp
        #:ethereum-lisp.crypto
        #:ethereum-lisp.trie
        #:ethereum-lisp.validation
        #:ethereum-lisp.accounts)
  (:export
   #:state-db
   #:make-state-db
   #:state-storage-proof
   #:make-state-storage-proof
   #:state-storage-proof-slot
   #:state-storage-proof-value
   #:state-storage-proof-proof
   #:state-proof-result
   #:make-state-proof-result
   #:state-proof-result-address
   #:state-proof-result-balance
   #:state-proof-result-nonce
   #:state-proof-result-code-hash
   #:state-proof-result-storage-root
   #:state-proof-result-account-proof
   #:state-proof-result-storage-proofs
   #:state-account-range-entry
   #:state-account-range-entry-proof-key
   #:state-account-range-entry-address
   #:state-account-range-entry-account
   #:state-account-range-entry-code
   #:state-account-range-entry-storage-entries
   #:state-storage-range-entry
   #:state-storage-range-entry-proof-key
   #:state-storage-range-entry-slot
   #:state-storage-range-entry-value
   #:state-db-get-account
   #:state-db-set-account
   #:state-db-clear-account
   #:state-db-set-code
   #:state-db-get-code
   #:state-db-get-code-hash
   #:state-db-copy
   #:state-db-restore
   #:state-db-set-storage
   #:state-db-get-storage
   #:state-db-get-storage-root
   #:state-db-get-storage-proof
   #:state-db-verify-storage-proof
   #:state-db-get-account-proof
   #:state-db-verify-account-proof
   #:state-db-get-proof
   #:state-db-verify-proof
   #:state-db-account-range
   #:state-db-storage-range
   #:state-db-for-each-account
   #:state-db-root
   #:state-db-root-hex
   #:+wei-per-gwei+
   #:state-db-add-balance))

(defpackage #:ethereum-lisp.state-proof-json
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.hex
        #:ethereum-lisp.types
        #:ethereum-lisp.state)
  (:export
   #:state-proof-result-rpc-object
   #:state-proof-result-from-rpc-object))

(ethereum-lisp.package-tools:reexport-symbols
 '#:ethereum-lisp.state
 '#:ethereum-lisp.state-proof-json
 '(#:state-proof-result-rpc-object
   #:state-proof-result-from-rpc-object))

(defpackage #:ethereum-lisp.genesis-state
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.types
        #:ethereum-lisp.validation
        #:ethereum-lisp.json
        #:ethereum-lisp.genesis
        #:ethereum-lisp.accounts
        #:ethereum-lisp.state)
  (:export
   #:apply-genesis-account
   #:apply-genesis-alloc
   #:state-db-from-genesis-alloc
   #:state-db-from-genesis-json-string
   #:state-db-from-genesis-json-file
   #:genesis-state-root-from-genesis-alloc
   #:genesis-state-root-from-genesis-json-string
   #:genesis-state-root-from-genesis-json-file
   #:validate-genesis-state-root
   #:validate-genesis-json-state-root
   #:genesis-header-from-state-genesis-object
   #:genesis-header-from-state-genesis-json-string
   #:genesis-header-from-state-genesis-json-file
   #:genesis-block-from-state-genesis-object
   #:genesis-block-from-state-genesis-json-string
   #:genesis-block-from-state-genesis-json-file))

(ethereum-lisp.package-tools:reexport-symbols
 '#:ethereum-lisp.state
 '#:ethereum-lisp.genesis-state
 '(#:apply-genesis-account
   #:apply-genesis-alloc
   #:state-db-from-genesis-alloc
   #:state-db-from-genesis-json-string
   #:state-db-from-genesis-json-file
   #:genesis-state-root-from-genesis-alloc
   #:genesis-state-root-from-genesis-json-string
   #:genesis-state-root-from-genesis-json-file
   #:validate-genesis-state-root
   #:validate-genesis-json-state-root
   #:genesis-header-from-state-genesis-object
   #:genesis-header-from-state-genesis-json-string
   #:genesis-header-from-state-genesis-json-file
   #:genesis-block-from-state-genesis-object
   #:genesis-block-from-state-genesis-json-string
   #:genesis-block-from-state-genesis-json-file))

(defpackage #:ethereum-lisp.evm.internal
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.rlp
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.accounts
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.consensus
        #:ethereum-lisp.kzg
        #:ethereum-lisp.state)
  (:export
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-selfdestructed-addresses
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:finalize-evm-selfdestructs
   #:execute-bytecode))

(defpackage #:ethereum-lisp.evm
  (:use #:cl)
  (:import-from #:ethereum-lisp.evm.internal
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-selfdestructed-addresses
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:finalize-evm-selfdestructs
   #:execute-bytecode)
  (:export
   #:evm-error
   #:precompile-address
   #:prewarm-precompile-addresses
   #:evm-context
   #:make-evm-context
   #:evm-context-state
   #:evm-context-address
   #:evm-context-caller
   #:evm-context-origin
   #:evm-context-call-value
   #:evm-context-gas-price
   #:evm-context-input
   #:evm-context-return-data
   #:evm-context-coinbase
   #:evm-context-timestamp
   #:evm-context-block-number
   #:evm-context-prev-randao
   #:evm-context-gas-limit
   #:evm-context-chain-id
   #:evm-context-chain-rules
   #:evm-context-base-fee
   #:evm-context-blob-hashes
   #:evm-context-blob-base-fee
   #:evm-context-transient-storage
   #:evm-context-storage-originals
   #:evm-context-storage-clears
   #:evm-context-selfdestructed-addresses
   #:evm-context-accessed-storage
   #:evm-context-accessed-addresses
   #:evm-context-block-hashes
   #:evm-context-read-only-p
   #:evm-result
   #:evm-result-status
   #:evm-result-stack
   #:evm-result-memory
   #:evm-result-return-data
   #:evm-result-logs
   #:evm-result-pc
   #:evm-result-gas-used
   #:evm-result-refund-counter
   #:finalize-evm-selfdestructs
   #:execute-bytecode))

(defpackage #:ethereum-lisp.execution
  (:shadow
   #:validate-access-list-fields
   #:validate-set-code-authorization-fields
   #:validate-set-code-transaction-fields
   #:validate-transaction-data-field
   #:validate-transaction-recipient-field)
  (:use #:cl
        #:ethereum-lisp.bytes
        #:ethereum-lisp.rlp
        #:ethereum-lisp.types
        #:ethereum-lisp.crypto
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.accounts
        #:ethereum-lisp.transactions
        #:ethereum-lisp.receipts
        #:ethereum-lisp.execution-requests
        #:ethereum-lisp.block-access-lists
        #:ethereum-lisp.blocks
        #:ethereum-lisp.consensus
        #:ethereum-lisp.state
        #:ethereum-lisp.evm)
  (:export
   #:execute-message-call
   #:apply-withdrawal
   #:apply-withdrawals
   #:transaction-validation-error
   #:transaction-intrinsic-gas
   #:apply-legacy-transaction
   #:apply-message
   #:apply-message-list
   #:execution-result
   #:make-execution-result
   #:execution-result-receipts
   #:execution-result-state-root
   #:execution-result-transactions-root
   #:execution-result-receipts-root
   #:execute-legacy-transactions
   #:apply-legacy-message
   #:apply-signed-message
   #:apply-signed-message-list
   #:execute-legacy-messages
   #:execute-signed-messages
   #:execute-legacy-block
   #:execute-signed-block))

(ethereum-lisp.package-tools:reexport-symbols
 '#:ethereum-lisp.state
 '#:ethereum-lisp.execution
 '(#:apply-withdrawal
   #:apply-withdrawals
   #:transaction-validation-error
   #:transaction-intrinsic-gas
   #:apply-legacy-transaction
   #:apply-message
   #:apply-message-list
   #:execution-result
   #:make-execution-result
   #:execution-result-receipts
   #:execution-result-state-root
   #:execution-result-transactions-root
   #:execution-result-receipts-root
   #:execute-legacy-transactions))

(defpackage #:ethereum-lisp.execution-service
  (:use #:cl
        #:ethereum-lisp.validation
        #:ethereum-lisp.chain-config
        #:ethereum-lisp.accounts
        #:ethereum-lisp.blocks
        #:ethereum-lisp.chain-store
        #:ethereum-lisp.state
        #:ethereum-lisp.execution)
  (:export
   #:execute-atomic-block-commit
   #:commit-state-db-to-chain-store
   #:chain-store-state-db
   #:execute-and-commit-engine-payload
   #:execute-and-commit-block
   #:execute-and-commit-signed-block))

(ethereum-lisp.package-tools:reexport-symbols
 '#:ethereum-lisp.execution
 '#:ethereum-lisp.execution-service
 '(#:execute-atomic-block-commit
   #:commit-state-db-to-chain-store
   #:chain-store-state-db
   #:execute-and-commit-engine-payload
   #:execute-and-commit-block
   #:execute-and-commit-signed-block))
